// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService || SqlBackupsService || SqlDatabasesService || SqlInstancesService || SqlOperationsService || SqlSslCertsService || SqlUsersService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Backup context.
  public struct BackupContext: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The identifier of the backup.
    public var backupId: Swift.Int64 = Swift.Int64()

    /// This is always `sql#backupContext`.
    public var kind: Swift.String = Swift.String()

    /// The name of the backup.
    /// Format: projects/{project}/backups/{backup}
    public var name: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `BackupContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BackupContext().with { $0.backupId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let backupId = CodingKeys(stringValue: "backupId")
      static let kind = CodingKeys(stringValue: "kind")
      static let name = CodingKeys(stringValue: "name")

      static let _knownKeys: Set<Swift.String> = [
        "backupId",
        "kind",
        "name",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .backupId) {
        self.backupId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
        self.kind = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.backupId, forKey: .backupId)
      try container.encode(self.kind, forKey: .kind)
      try container.encode(self.name, forKey: .name)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.BackupContext"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
