// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BlueGreenDeploymentsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for managing blue-green deployments.
  ///
  /// @Snippet(path: "BlueGreenDeploymentsServiceQuickstart")
  public final class BlueGreenDeploymentsServiceClient: Clients.BlueGreenDeploymentsServiceProtocol,
    Sendable
  {
    let inner: any Clients.BlueGreenDeploymentsServiceStub

    /// Creates a new `BlueGreenDeploymentsServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.BlueGreenDeploymentsServiceStub =
        try Clients.BlueGreenDeploymentsServiceTransport(options)
      inner = Clients.BlueGreenDeploymentsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.BlueGreenDeploymentsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Creates a blue-green deployment under a given project and location.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_CreateBlueGreenDeployment")
    public func createBlueGreenDeployment(
      request: CreateBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.createBlueGreenDeployment(request: request, options: options)
    }

    /// Retrieves a blue-green deployment resource under a given project and
    /// location.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_GetBlueGreenDeployment")
    public func getBlueGreenDeployment(
      request: GetBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BlueGreenDeployment {
      try await self.inner.getBlueGreenDeployment(request: request, options: options)
    }

    /// Switches over to green instance for a blue-green deployment.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_SwitchoverBlueGreenDeployment")
    public func switchoverBlueGreenDeployment(
      request: SwitchoverBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.switchoverBlueGreenDeployment(request: request, options: options)
    }

    /// Lists blue-green deployments under a given project.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_ListBlueGreenDeployments")
    public func listBlueGreenDeployments(
      request: ListBlueGreenDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse {
      try await self.inner.listBlueGreenDeployments(request: request, options: options)
    }

    /// Deletes a blue-green deployment.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_DeleteBlueGreenDeployment")
    public func deleteBlueGreenDeployment(
      request: DeleteBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.deleteBlueGreenDeployment(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `BlueGreenDeploymentsServiceClient`.
    ///
    /// To mock `BlueGreenDeploymentsServiceClient` change your functions to receive
    /// `some BlueGreenDeploymentsServiceProtocol` or `any BlueGreenDeploymentsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol BlueGreenDeploymentsServiceProtocol: Sendable {
      /// See `BlueGreenDeploymentsServiceClient.createBlueGreenDeployment`.
      func createBlueGreenDeployment(
        request: CreateBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `BlueGreenDeploymentsServiceClient.getBlueGreenDeployment`.
      func getBlueGreenDeployment(
        request: GetBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.BlueGreenDeployment

      /// See `BlueGreenDeploymentsServiceClient.switchoverBlueGreenDeployment`.
      func switchoverBlueGreenDeployment(
        request: SwitchoverBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `BlueGreenDeploymentsServiceClient.listBlueGreenDeployments`.
      func listBlueGreenDeployments(
        request: ListBlueGreenDeploymentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse

      /// See `BlueGreenDeploymentsServiceClient.deleteBlueGreenDeployment`.
      func deleteBlueGreenDeployment(
        request: DeleteBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation
    }
  }

  // Default implementations
  extension Clients.BlueGreenDeploymentsServiceProtocol {
    public func createBlueGreenDeployment(request: CreateBlueGreenDeploymentRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.createBlueGreenDeployment(request: request, options: .init())
    }

    public func createBlueGreenDeployment(
      request: CreateBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createBlueGreenDeployment(
      parent: Swift.String,
      blueGreenDeployment: BlueGreenDeployment?,
      blueGreenDeploymentId: Swift.String,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = CreateBlueGreenDeploymentRequest().with {
        $0.parent = parent
        $0.blueGreenDeployment = blueGreenDeployment
        $0.blueGreenDeploymentId = blueGreenDeploymentId
      }
      return try await self.createBlueGreenDeployment(request: request)
    }

    public func getBlueGreenDeployment(request: GetBlueGreenDeploymentRequest) async throws
      -> GoogleCloudSqlV1.BlueGreenDeployment
    {
      try await self.getBlueGreenDeployment(request: request, options: .init())
    }

    public func getBlueGreenDeployment(
      request: GetBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BlueGreenDeployment {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getBlueGreenDeployment(
      name: Swift.String,
    ) async throws -> GoogleCloudSqlV1.BlueGreenDeployment {
      let request = GetBlueGreenDeploymentRequest().with {
        $0.name = name
      }
      return try await self.getBlueGreenDeployment(request: request)
    }

    public func switchoverBlueGreenDeployment(request: SwitchoverBlueGreenDeploymentRequest)
      async throws -> GoogleCloudSqlV1.Operation
    {
      try await self.switchoverBlueGreenDeployment(request: request, options: .init())
    }

    public func switchoverBlueGreenDeployment(
      request: SwitchoverBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func switchoverBlueGreenDeployment(
      name: Swift.String,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = SwitchoverBlueGreenDeploymentRequest().with {
        $0.name = name
      }
      return try await self.switchoverBlueGreenDeployment(request: request)
    }

    public func listBlueGreenDeployments(request: ListBlueGreenDeploymentsRequest) async throws
      -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse
    {
      try await self.listBlueGreenDeployments(request: request, options: .init())
    }

    public func listBlueGreenDeployments(
      request: ListBlueGreenDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listBlueGreenDeploymentsByItems(
      request: ListBlueGreenDeploymentsRequest
    ) -> some AsyncSequence<BlueGreenDeployment, any Swift.Error> & Sendable {
      self.listBlueGreenDeploymentsByItems(request: request, options: .init())
    }

    /// Lists blue-green deployments under a given project.
    ///
    /// @Snippet(path: "BlueGreenDeploymentsService_ListBlueGreenDeployments")
    public func listBlueGreenDeploymentsByItems(
      request: ListBlueGreenDeploymentsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<BlueGreenDeployment, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse in
        var request = request
        request.pageToken = token
        return try await self.listBlueGreenDeployments(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listBlueGreenDeploymentsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<BlueGreenDeployment, any Swift.Error> & Sendable {
      let request = ListBlueGreenDeploymentsRequest().with {
        $0.parent = parent
      }
      return self.listBlueGreenDeploymentsByItems(request: request)
    }

    public func deleteBlueGreenDeployment(request: DeleteBlueGreenDeploymentRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.deleteBlueGreenDeployment(request: request, options: .init())
    }

    public func deleteBlueGreenDeployment(
      request: DeleteBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteBlueGreenDeployment(
      name: Swift.String,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = DeleteBlueGreenDeploymentRequest().with {
        $0.name = name
      }
      return try await self.deleteBlueGreenDeployment(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'BlueGreenDeploymentsService' trait in Package.swift to use this client."
  )
  public final class BlueGreenDeploymentsServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'BlueGreenDeploymentsService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
