// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BlueGreenDeploymentsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleGax
  import struct Logging.Logger

  extension Clients {
    final class BlueGreenDeploymentsServiceLogging: BlueGreenDeploymentsServiceStub {
      let inner: any BlueGreenDeploymentsServiceStub
      let logger: Logger

      public init(_ inner: any BlueGreenDeploymentsServiceStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "google-cloud-sql-v1"
        logger[metadataKey: "gcp.client.service"] = "sqladmin"
        logger[metadataKey: "gcp.experimental.swift.client"] = "BlueGreenDeploymentsService"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func createBlueGreenDeployment(
        request: CreateBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "createBlueGreenDeployment",
          action: {
            (r: CreateBlueGreenDeploymentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.createBlueGreenDeployment(request: r, options: o)
          })
      }

      public func getBlueGreenDeployment(
        request: GetBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.BlueGreenDeployment {
        try await self._intercept(
          request: request,
          options: options,
          name: "getBlueGreenDeployment",
          action: {
            (r: GetBlueGreenDeploymentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.BlueGreenDeployment
            in
            return try await self.inner.getBlueGreenDeployment(request: r, options: o)
          })
      }

      public func switchoverBlueGreenDeployment(
        request: SwitchoverBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "switchoverBlueGreenDeployment",
          action: {
            (r: SwitchoverBlueGreenDeploymentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.switchoverBlueGreenDeployment(request: r, options: o)
          })
      }

      public func listBlueGreenDeployments(
        request: ListBlueGreenDeploymentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listBlueGreenDeployments",
          action: {
            (r: ListBlueGreenDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.ListBlueGreenDeploymentsResponse
            in
            return try await self.inner.listBlueGreenDeployments(request: r, options: o)
          })
      }

      public func deleteBlueGreenDeployment(
        request: DeleteBlueGreenDeploymentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteBlueGreenDeployment",
          action: {
            (r: DeleteBlueGreenDeploymentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.deleteBlueGreenDeployment(request: r, options: o)
          })
      }
    }
  }
#endif
