// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// A Cloud SQL instance resource.
  public struct DatabaseInstance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// This is always `sql#instance`.
    public var kind: Swift.String

    /// The current serving state of the Cloud SQL instance.
    public var state: DatabaseInstance.SqlInstanceState

    /// The database engine type and version. The `databaseVersion` field cannot
    /// be changed after instance creation.
    public var databaseVersion: SqlDatabaseVersion

    /// The user settings.
    public var settings: Settings?

    /// This field is deprecated and will be removed from a future version of the
    /// API. Use the `settings.settingsVersion` field instead.
    public var etag: Swift.String

    /// The name and status of the failover replica.
    public var failoverReplica: DatabaseInstance.SqlFailoverReplica?

    /// The name of the instance which will act as primary in the replication
    /// setup.
    public var masterInstanceName: Swift.String

    /// The replicas of the instance.
    public var replicaNames: [Swift.String]

    /// The maximum disk size of the instance in bytes.
    public var maxDiskSize: GoogleCloudWkt.Int64Value?

    /// The current disk usage of the instance in bytes. This property has been
    /// deprecated. Use the
    /// "cloudsql.googleapis.com/database/disk/bytes_used" metric in Cloud
    /// Monitoring API instead. Please see [this
    /// announcement](https://groups.google.com/d/msg/google-cloud-sql-announce/I_7-F9EBhT0/BtvFtdFeAgAJ)
    /// for details.
    public var currentDiskSize: GoogleCloudWkt.Int64Value?

    /// The assigned IP addresses for the instance.
    public var ipAddresses: [IpMapping]

    /// SSL configuration.
    public var serverCaCert: SslCert?

    /// The instance type.
    public var instanceType: SqlInstanceType

    /// The project ID of the project containing the Cloud SQL instance. The Google
    /// apps domain is prefixed if applicable.
    public var project: Swift.String

    /// The IPv6 address assigned to the instance.
    /// (Deprecated) This property was applicable only
    /// to First Generation instances.
    public var ipv6Address: Swift.String

    /// The service account email address assigned to the instance.\This
    /// property is read-only.
    public var serviceAccountEmailAddress: Swift.String

    /// Configuration specific to on-premises instances.
    public var onPremisesConfiguration: OnPremisesConfiguration?

    /// Configuration specific to failover replicas and read replicas.
    public var replicaConfiguration: ReplicaConfiguration?

    /// The backend type.
    /// `SECOND_GEN`: Cloud SQL database instance.
    /// `EXTERNAL`: A database server that is not managed by Google.
    ///
    /// This property is read-only; use the `tier` property in the `settings`
    /// object to determine the database type.
    public var backendType: SqlBackendType

    /// The URI of this resource.
    public var selfLink: Swift.String

    /// If the instance state is SUSPENDED, the reason for the suspension.
    public var suspensionReason: [SqlSuspensionReason]

    /// Connection name of the Cloud SQL instance used in connection strings.
    public var connectionName: Swift.String

    /// Name of the Cloud SQL instance. This does not include the project ID.
    public var name: Swift.String

    /// The geographical region of the Cloud SQL instance.
    ///
    /// It can be one of the
    /// [regions](https://cloud.google.com/sql/docs/mysql/locations#location-r)
    /// where Cloud SQL operates:
    ///
    /// For example,  `asia-east1`, `europe-west1`, and  `us-central1`.
    /// The default value is `us-central1`.
    public var region: Swift.String

    /// The Compute Engine zone that the instance is currently serving from. This
    /// value could be different from the zone that was specified when the instance
    /// was created if the instance has failed over to its secondary zone. WARNING:
    /// Changing this might restart the instance.
    public var gceZone: Swift.String

    /// The Compute Engine zone that the failover instance is currently serving
    /// from for a regional instance. This value could be different
    /// from the zone that was specified when the instance
    /// was created if the instance has failed over to its secondary/failover zone.
    public var secondaryGceZone: Swift.String

    /// Disk encryption configuration specific to an instance.
    public var diskEncryptionConfiguration: DiskEncryptionConfiguration?

    /// Disk encryption status specific to an instance.
    public var diskEncryptionStatus: DiskEncryptionStatus?

    /// Initial root password. Use only on creation. You must set root passwords
    /// before you can connect to PostgreSQL instances.
    public var rootPassword: Swift.String

    /// The start time of any upcoming scheduled maintenance for this instance.
    public var scheduledMaintenance: DatabaseInstance.SqlScheduledMaintenance?

    /// This status indicates whether the instance satisfies PZS.
    ///
    /// The status is reserved for future use.
    public var satisfiesPzs: GoogleCloudWkt.BoolValue?

    /// Output only. Stores the current database version running on the instance
    /// including minor version such as `MYSQL_8_0_18`.
    public var databaseInstalledVersion: Swift.String

    /// This field represents the report generated by the proactive database
    /// wellness job for OutOfDisk issues.
    /// *  Writers:
    ///   *  the proactive database wellness job for OOD.
    /// *  Readers:
    ///   *  the proactive database wellness job
    public var outOfDiskReport: DatabaseInstance.SqlOutOfDiskReport?

    /// Output only. The time when the instance was created in
    /// [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example
    /// `2012-11-15T16:19:00.094Z`.
    public var createTime: GoogleCloudWkt.Timestamp?

    /// Output only. List all maintenance versions applicable on the instance
    public var availableMaintenanceVersions: [Swift.String]

    /// The current software version on the instance.
    public var maintenanceVersion: Swift.String

    /// Output only. All database versions that are available for upgrade.
    public var upgradableDatabaseVersions: [AvailableDatabaseVersion]

    public var sqlNetworkArchitecture: DatabaseInstance.SqlNetworkArchitecture?

    /// Output only. The link to service attachment of PSC instance.
    public var pscServiceAttachmentLink: Swift.String?

    /// Output only. The dns name of the instance.
    public var dnsName: Swift.String?

    /// Output only. DEPRECATED: please use write_endpoint instead.
    public var primaryDnsName: Swift.String?

    /// Output only. The dns name of the primary instance in a replication group.
    public var writeEndpoint: Swift.String?

    /// Optional. A primary instance and disaster recovery (DR) replica pair.
    /// A DR replica is a cross-region replica that you designate
    /// for failover in the event that the primary instance
    /// experiences regional failure.
    /// Applicable to MySQL and PostgreSQL.
    public var replicationCluster: ReplicationCluster?

    /// Gemini instance configuration.
    public var geminiConfig: GeminiInstanceConfig?

    /// Output only. This status indicates whether the instance satisfies PZI.
    ///
    /// The status is reserved for future use.
    public var satisfiesPzi: GoogleCloudWkt.BoolValue?

    /// Input only. Whether Cloud SQL is enabled to switch storing point-in-time
    /// recovery log files from a data disk to Cloud Storage.
    public var switchTransactionLogsToCloudStorageEnabled: GoogleCloudWkt.BoolValue?

    /// Input only. Determines whether an in-place major version upgrade of
    /// replicas happens when an in-place major version upgrade of a primary
    /// instance is initiated.
    public var includeReplicasForMajorVersionUpgrade: GoogleCloudWkt.BoolValue?

    /// Optional. Input only. Immutable. Tag keys and tag values that are bound to
    /// this instance. You must represent each item in the map as:
    /// `"<tag-key-namespaced-name>" : "<tag-value-short-name>"`.
    ///
    /// For example, a single resource can have the following tags:
    /// ```
    ///   "123/environment": "production",
    ///   "123/costCenter": "marketing",
    /// ```
    ///
    /// For more information on tag creation and management, see
    /// https://cloud.google.com/resource-manager/docs/tags/tags-overview.
    public var tags: [Swift.String: Swift.String]

    /// The number of read pool nodes in a read pool.
    public var nodeCount: Swift.Int32?

    /// Output only. Entries containing information about each read pool node of
    /// the read pool.
    public var nodes: [DatabaseInstance.PoolNodeConfig]

    /// Output only. The list of DNS names used by this instance.
    public var dnsNames: [DnsNameMapping]

    /// Initialize a new instance of `DatabaseInstance`.
    public init(
      kind: Swift.String = Swift.String(),
      state: DatabaseInstance.SqlInstanceState = DatabaseInstance.SqlInstanceState(),
      databaseVersion: SqlDatabaseVersion = SqlDatabaseVersion(),
      settings: Settings? = nil,
      etag: Swift.String = Swift.String(),
      failoverReplica: DatabaseInstance.SqlFailoverReplica? = nil,
      masterInstanceName: Swift.String = Swift.String(),
      replicaNames: [Swift.String] = [],
      maxDiskSize: GoogleCloudWkt.Int64Value? = nil,
      currentDiskSize: GoogleCloudWkt.Int64Value? = nil,
      ipAddresses: [IpMapping] = [],
      serverCaCert: SslCert? = nil,
      instanceType: SqlInstanceType = SqlInstanceType(),
      project: Swift.String = Swift.String(),
      ipv6Address: Swift.String = Swift.String(),
      serviceAccountEmailAddress: Swift.String = Swift.String(),
      onPremisesConfiguration: OnPremisesConfiguration? = nil,
      replicaConfiguration: ReplicaConfiguration? = nil,
      backendType: SqlBackendType = SqlBackendType(),
      selfLink: Swift.String = Swift.String(),
      suspensionReason: [SqlSuspensionReason] = [],
      connectionName: Swift.String = Swift.String(),
      name: Swift.String = Swift.String(),
      region: Swift.String = Swift.String(),
      gceZone: Swift.String = Swift.String(),
      secondaryGceZone: Swift.String = Swift.String(),
      diskEncryptionConfiguration: DiskEncryptionConfiguration? = nil,
      diskEncryptionStatus: DiskEncryptionStatus? = nil,
      rootPassword: Swift.String = Swift.String(),
      scheduledMaintenance: DatabaseInstance.SqlScheduledMaintenance? = nil,
      satisfiesPzs: GoogleCloudWkt.BoolValue? = nil,
      databaseInstalledVersion: Swift.String = Swift.String(),
      outOfDiskReport: DatabaseInstance.SqlOutOfDiskReport? = nil,
      createTime: GoogleCloudWkt.Timestamp? = nil,
      availableMaintenanceVersions: [Swift.String] = [],
      maintenanceVersion: Swift.String = Swift.String(),
      upgradableDatabaseVersions: [AvailableDatabaseVersion] = [],
      sqlNetworkArchitecture: DatabaseInstance.SqlNetworkArchitecture? = nil,
      pscServiceAttachmentLink: Swift.String? = nil,
      dnsName: Swift.String? = nil,
      primaryDnsName: Swift.String? = nil,
      writeEndpoint: Swift.String? = nil,
      replicationCluster: ReplicationCluster? = nil,
      geminiConfig: GeminiInstanceConfig? = nil,
      satisfiesPzi: GoogleCloudWkt.BoolValue? = nil,
      switchTransactionLogsToCloudStorageEnabled: GoogleCloudWkt.BoolValue? = nil,
      includeReplicasForMajorVersionUpgrade: GoogleCloudWkt.BoolValue? = nil,
      tags: [Swift.String: Swift.String] = [:],
      nodeCount: Swift.Int32? = nil,
      nodes: [DatabaseInstance.PoolNodeConfig] = [],
      dnsNames: [DnsNameMapping] = [],
    ) {
      self.kind = kind
      self.state = state
      self.databaseVersion = databaseVersion
      self.settings = settings
      self.etag = etag
      self.failoverReplica = failoverReplica
      self.masterInstanceName = masterInstanceName
      self.replicaNames = replicaNames
      self.maxDiskSize = maxDiskSize
      self.currentDiskSize = currentDiskSize
      self.ipAddresses = ipAddresses
      self.serverCaCert = serverCaCert
      self.instanceType = instanceType
      self.project = project
      self.ipv6Address = ipv6Address
      self.serviceAccountEmailAddress = serviceAccountEmailAddress
      self.onPremisesConfiguration = onPremisesConfiguration
      self.replicaConfiguration = replicaConfiguration
      self.backendType = backendType
      self.selfLink = selfLink
      self.suspensionReason = suspensionReason
      self.connectionName = connectionName
      self.name = name
      self.region = region
      self.gceZone = gceZone
      self.secondaryGceZone = secondaryGceZone
      self.diskEncryptionConfiguration = diskEncryptionConfiguration
      self.diskEncryptionStatus = diskEncryptionStatus
      self.rootPassword = rootPassword
      self.scheduledMaintenance = scheduledMaintenance
      self.satisfiesPzs = satisfiesPzs
      self.databaseInstalledVersion = databaseInstalledVersion
      self.outOfDiskReport = outOfDiskReport
      self.createTime = createTime
      self.availableMaintenanceVersions = availableMaintenanceVersions
      self.maintenanceVersion = maintenanceVersion
      self.upgradableDatabaseVersions = upgradableDatabaseVersions
      self.sqlNetworkArchitecture = sqlNetworkArchitecture
      self.pscServiceAttachmentLink = pscServiceAttachmentLink
      self.dnsName = dnsName
      self.primaryDnsName = primaryDnsName
      self.writeEndpoint = writeEndpoint
      self.replicationCluster = replicationCluster
      self.geminiConfig = geminiConfig
      self.satisfiesPzi = satisfiesPzi
      self.switchTransactionLogsToCloudStorageEnabled = switchTransactionLogsToCloudStorageEnabled
      self.includeReplicasForMajorVersionUpgrade = includeReplicasForMajorVersionUpgrade
      self.tags = tags
      self.nodeCount = nodeCount
      self.nodes = nodes
      self.dnsNames = dnsNames
    }

    public struct SqlFailoverReplica: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The name of the failover replica. If specified at instance creation, a
      /// failover replica is created for the instance. The name
      /// doesn't include the project ID.
      public var name: Swift.String

      /// The availability status of the failover replica. A false status indicates
      /// that the failover replica is out of sync. The primary instance can only
      /// failover to the failover replica when the status is true.
      public var available: GoogleCloudWkt.BoolValue?

      /// Initialize a new instance of `SqlFailoverReplica`.
      public init(
        name: Swift.String = Swift.String(),
        available: GoogleCloudWkt.BoolValue? = nil,
      ) {
        self.name = name
        self.available = available
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.sql.v1.DatabaseInstance.SqlFailoverReplica"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Any scheduled maintenance for this instance.
    public struct SqlScheduledMaintenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The start time of any upcoming scheduled maintenance for this instance.
      public var startTime: GoogleCloudWkt.Timestamp?

      public var canDefer: Swift.Bool

      /// If the scheduled maintenance can be rescheduled.
      public var canReschedule: Swift.Bool

      /// Maintenance cannot be rescheduled to start beyond this deadline.
      public var scheduleDeadlineTime: GoogleCloudWkt.Timestamp?

      /// Initialize a new instance of `SqlScheduledMaintenance`.
      public init(
        startTime: GoogleCloudWkt.Timestamp? = nil,
        canDefer: Swift.Bool = Swift.Bool(),
        canReschedule: Swift.Bool = Swift.Bool(),
        scheduleDeadlineTime: GoogleCloudWkt.Timestamp? = nil,
      ) {
        self.startTime = startTime
        self.canDefer = canDefer
        self.canReschedule = canReschedule
        self.scheduleDeadlineTime = scheduleDeadlineTime
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.sql.v1.DatabaseInstance.SqlScheduledMaintenance"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// This message wraps up the information written by out-of-disk detection job.
    public struct SqlOutOfDiskReport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// This field represents the state generated by the proactive database
      /// wellness job for OutOfDisk issues.
      /// *  Writers:
      ///   *  the proactive database wellness job for OOD.
      /// *  Readers:
      ///   *  the proactive database wellness job
      public var sqlOutOfDiskState: DatabaseInstance.SqlOutOfDiskReport.SqlOutOfDiskState?

      /// The minimum recommended increase size in GigaBytes
      /// This field is consumed by the frontend
      /// *  Writers:
      ///   *  the proactive database wellness job for OOD.
      /// *  Readers:
      public var sqlMinRecommendedIncreaseSizeGb: Swift.Int32?

      /// Initialize a new instance of `SqlOutOfDiskReport`.
      public init(
        sqlOutOfDiskState: DatabaseInstance.SqlOutOfDiskReport.SqlOutOfDiskState? = nil,
        sqlMinRecommendedIncreaseSizeGb: Swift.Int32? = nil,
      ) {
        self.sqlOutOfDiskState = sqlOutOfDiskState
        self.sqlMinRecommendedIncreaseSizeGb = sqlMinRecommendedIncreaseSizeGb
      }

      /// This enum lists all possible states regarding out-of-disk issues.
      public enum SqlOutOfDiskState: Codable, Equatable, Sendable {
        case unspecified
        case normal
        case softShutdown
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .normal: return 1
          case .softShutdown: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: String? {
          switch self {
          case .unspecified: return "SQL_OUT_OF_DISK_STATE_UNSPECIFIED"
          case .normal: return "NORMAL"
          case .softShutdown: return "SOFT_SHUTDOWN"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
        public init(stringValue: String) {
          switch stringValue {
          case "SQL_OUT_OF_DISK_STATE_UNSPECIFIED": self = .unspecified
          case "NORMAL": self = .normal
          case "SOFT_SHUTDOWN": self = .softShutdown
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .normal
          case 2: self = .softShutdown
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .normal: return try container.encode(1)
          case .softShutdown: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.sql.v1.DatabaseInstance.SqlOutOfDiskReport"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Details of a single read pool node of a read pool.
    public struct PoolNodeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. The name of the read pool node, to be used for retrieving
      /// metrics and logs.
      public var name: Swift.String?

      /// Output only. The zone of the read pool node.
      public var gceZone: Swift.String?

      /// Output only. Mappings containing IP addresses that can be used to connect
      /// to the read pool node.
      public var ipAddresses: [IpMapping]

      /// Output only. The DNS name of the read pool node.
      public var dnsName: Swift.String?

      /// Output only. The current state of the read pool node.
      public var state: DatabaseInstance.SqlInstanceState?

      /// Output only. The list of DNS names used by this read pool node.
      public var dnsNames: [DnsNameMapping]

      /// Output only. The Private Service Connect (PSC) service attachment of the
      /// read pool node.
      public var pscServiceAttachmentLink: Swift.String?

      /// Output only. The list of settings for requested automatically-setup
      /// Private Service Connect (PSC) consumer endpoints that can be used to
      /// connect to this read pool node.
      public var pscAutoConnections: [PscAutoConnectionConfig]

      /// Initialize a new instance of `PoolNodeConfig`.
      public init(
        name: Swift.String? = nil,
        gceZone: Swift.String? = nil,
        ipAddresses: [IpMapping] = [],
        dnsName: Swift.String? = nil,
        state: DatabaseInstance.SqlInstanceState? = nil,
        dnsNames: [DnsNameMapping] = [],
        pscServiceAttachmentLink: Swift.String? = nil,
        pscAutoConnections: [PscAutoConnectionConfig] = [],
      ) {
        self.name = name
        self.gceZone = gceZone
        self.ipAddresses = ipAddresses
        self.dnsName = dnsName
        self.state = state
        self.dnsNames = dnsNames
        self.pscServiceAttachmentLink = pscServiceAttachmentLink
        self.pscAutoConnections = pscAutoConnections
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.sql.v1.DatabaseInstance.PoolNodeConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The current serving state of the database instance.
    public enum SqlInstanceState: Codable, Equatable, Sendable {
      case unspecified
      case runnable
      case suspended
      case pendingDelete
      case pendingCreate
      case maintenance
      case failed
      case onlineMaintenance
      case repairing
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .runnable: return 1
        case .suspended: return 2
        case .pendingDelete: return 3
        case .pendingCreate: return 4
        case .maintenance: return 5
        case .failed: return 6
        case .onlineMaintenance: return 7
        case .repairing: return 8
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "SQL_INSTANCE_STATE_UNSPECIFIED"
        case .runnable: return "RUNNABLE"
        case .suspended: return "SUSPENDED"
        case .pendingDelete: return "PENDING_DELETE"
        case .pendingCreate: return "PENDING_CREATE"
        case .maintenance: return "MAINTENANCE"
        case .failed: return "FAILED"
        case .onlineMaintenance: return "ONLINE_MAINTENANCE"
        case .repairing: return "REPAIRING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "SQL_INSTANCE_STATE_UNSPECIFIED": self = .unspecified
        case "RUNNABLE": self = .runnable
        case "SUSPENDED": self = .suspended
        case "PENDING_DELETE": self = .pendingDelete
        case "PENDING_CREATE": self = .pendingCreate
        case "MAINTENANCE": self = .maintenance
        case "FAILED": self = .failed
        case "ONLINE_MAINTENANCE": self = .onlineMaintenance
        case "REPAIRING": self = .repairing
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .runnable
        case 2: self = .suspended
        case 3: self = .pendingDelete
        case 4: self = .pendingCreate
        case 5: self = .maintenance
        case 6: self = .failed
        case 7: self = .onlineMaintenance
        case 8: self = .repairing
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .runnable: return try container.encode(1)
        case .suspended: return try container.encode(2)
        case .pendingDelete: return try container.encode(3)
        case .pendingCreate: return try container.encode(4)
        case .maintenance: return try container.encode(5)
        case .failed: return try container.encode(6)
        case .onlineMaintenance: return try container.encode(7)
        case .repairing: return try container.encode(8)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The SQL network architecture for the instance.
    public enum SqlNetworkArchitecture: Codable, Equatable, Sendable {
      case unspecified
      case newNetworkArchitecture
      case oldNetworkArchitecture
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .newNetworkArchitecture: return 1
        case .oldNetworkArchitecture: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "SQL_NETWORK_ARCHITECTURE_UNSPECIFIED"
        case .newNetworkArchitecture: return "NEW_NETWORK_ARCHITECTURE"
        case .oldNetworkArchitecture: return "OLD_NETWORK_ARCHITECTURE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "SQL_NETWORK_ARCHITECTURE_UNSPECIFIED": self = .unspecified
        case "NEW_NETWORK_ARCHITECTURE": self = .newNetworkArchitecture
        case "OLD_NETWORK_ARCHITECTURE": self = .oldNetworkArchitecture
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .newNetworkArchitecture
        case 2: self = .oldNetworkArchitecture
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .newNetworkArchitecture: return try container.encode(1)
        case .oldNetworkArchitecture: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.DatabaseInstance"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
