// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Database instance demote primary instance context.
  public struct DemoteMasterContext: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// This is always `sql#demoteMasterContext`.
    public var kind: Swift.String = Swift.String()

    /// Verify the GTID consistency for demote operation. Default value:
    /// `True`. Setting this flag to `false` enables you to bypass the GTID
    /// consistency check between on-premises primary instance and Cloud SQL
    /// instance during the demotion operation but also exposes you to the risk of
    /// future replication failures. Change the value only if you know the reason
    /// for the GTID divergence and are confident that doing so will not cause any
    /// replication issues.
    public var verifyGtidConsistency: GoogleCloudWKT.BoolValue? = nil

    /// The name of the instance which will act as on-premises primary instance
    /// in the replication setup.
    public var masterInstanceName: Swift.String = Swift.String()

    /// Configuration specific to read-replicas replicating from the on-premises
    /// primary instance.
    public var replicaConfiguration: DemoteMasterConfiguration? = nil

    /// Flag to skip replication setup on the instance.
    public var skipReplicationSetup: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `DemoteMasterContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DemoteMasterContext().with { $0.kind = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kind = CodingKeys(stringValue: "kind")
      static let verifyGtidConsistency = CodingKeys(stringValue: "verifyGtidConsistency")
      static let masterInstanceName = CodingKeys(stringValue: "masterInstanceName")
      static let replicaConfiguration = CodingKeys(stringValue: "replicaConfiguration")
      static let skipReplicationSetup = CodingKeys(stringValue: "skipReplicationSetup")

      static let _knownKeys: Set<Swift.String> = [
        "kind",
        "verifyGtidConsistency",
        "masterInstanceName",
        "replicaConfiguration",
        "skipReplicationSetup",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
        self.kind = value
      }
      self.verifyGtidConsistency = try container.decodeIfPresent(
        GoogleCloudWKT.BoolValue.self, forKey: .verifyGtidConsistency)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .masterInstanceName) {
        self.masterInstanceName = value
      }
      self.replicaConfiguration = try container.decodeIfPresent(
        DemoteMasterConfiguration.self, forKey: .replicaConfiguration)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipReplicationSetup) {
        self.skipReplicationSetup = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kind, forKey: .kind)
      try container.encodeIfPresent(self.verifyGtidConsistency, forKey: .verifyGtidConsistency)
      try container.encode(self.masterInstanceName, forKey: .masterInstanceName)
      try container.encodeIfPresent(self.replicaConfiguration, forKey: .replicaConfiguration)
      try container.encode(self.skipReplicationSetup, forKey: .skipReplicationSetup)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.DemoteMasterContext"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
