// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Read-replica configuration specific to MySQL databases.
  public struct DemoteMasterMySqlReplicaConfiguration: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// This is always `sql#demoteMasterMysqlReplicaConfiguration`.
    public var kind: Swift.String = Swift.String()

    /// The username for the replication connection.
    public var username: Swift.String = Swift.String()

    /// The password for the replication connection.
    public var password: Swift.String = Swift.String()

    /// PEM representation of the replica's private key. The corresponding public
    /// key is encoded in the client's certificate. The format of the replica's
    /// private key can be either PKCS #1 or PKCS #8.
    public var clientKey: Swift.String = Swift.String()

    /// PEM representation of the replica's x509 certificate.
    public var clientCertificate: Swift.String = Swift.String()

    /// PEM representation of the trusted CA's x509 certificate.
    public var caCertificate: Swift.String = Swift.String()

    /// Initialize a new instance of `DemoteMasterMySqlReplicaConfiguration`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DemoteMasterMySqlReplicaConfiguration().with { $0.kind = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.DemoteMasterMySqlReplicaConfiguration"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
