// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Gemini instance configuration.
  public struct GeminiInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Whether Gemini is enabled.
    public var entitled: Swift.Bool? = nil

    /// Output only. Whether the vacuum management is enabled.
    public var googleVacuumMgmtEnabled: Swift.Bool? = nil

    /// Output only. Whether canceling the out-of-memory (OOM) session is enabled.
    public var oomSessionCancelEnabled: Swift.Bool? = nil

    /// Output only. Whether the active query is enabled.
    public var activeQueryEnabled: Swift.Bool? = nil

    /// Output only. Whether the index advisor is enabled.
    public var indexAdvisorEnabled: Swift.Bool? = nil

    /// Output only. Whether the flag recommender is enabled.
    public var flagRecommenderEnabled: Swift.Bool? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GeminiInstanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GeminiInstanceConfig().with { $0.entitled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let entitled = CodingKeys(stringValue: "entitled")
      static let googleVacuumMgmtEnabled = CodingKeys(stringValue: "googleVacuumMgmtEnabled")
      static let oomSessionCancelEnabled = CodingKeys(stringValue: "oomSessionCancelEnabled")
      static let activeQueryEnabled = CodingKeys(stringValue: "activeQueryEnabled")
      static let indexAdvisorEnabled = CodingKeys(stringValue: "indexAdvisorEnabled")
      static let flagRecommenderEnabled = CodingKeys(stringValue: "flagRecommenderEnabled")

      static let _knownKeys: Set<Swift.String> = [
        "entitled",
        "googleVacuumMgmtEnabled",
        "oomSessionCancelEnabled",
        "activeQueryEnabled",
        "indexAdvisorEnabled",
        "flagRecommenderEnabled",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.entitled = try container.decodeIfPresent(Swift.Bool.self, forKey: .entitled)
      self.googleVacuumMgmtEnabled = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .googleVacuumMgmtEnabled)
      self.oomSessionCancelEnabled = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .oomSessionCancelEnabled)
      self.activeQueryEnabled = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .activeQueryEnabled)
      self.indexAdvisorEnabled = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .indexAdvisorEnabled)
      self.flagRecommenderEnabled = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .flagRecommenderEnabled)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.entitled, forKey: .entitled)
      try container.encodeIfPresent(self.googleVacuumMgmtEnabled, forKey: .googleVacuumMgmtEnabled)
      try container.encodeIfPresent(self.oomSessionCancelEnabled, forKey: .oomSessionCancelEnabled)
      try container.encodeIfPresent(self.activeQueryEnabled, forKey: .activeQueryEnabled)
      try container.encodeIfPresent(self.indexAdvisorEnabled, forKey: .indexAdvisorEnabled)
      try container.encodeIfPresent(self.flagRecommenderEnabled, forKey: .flagRecommenderEnabled)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.GeminiInstanceConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
