// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Gemini instance configuration.
  public struct GeminiInstanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Whether Gemini is enabled.
    public var entitled: Swift.Bool?

    /// Output only. Whether the vacuum management is enabled.
    public var googleVacuumMgmtEnabled: Swift.Bool?

    /// Output only. Whether canceling the out-of-memory (OOM) session is enabled.
    public var oomSessionCancelEnabled: Swift.Bool?

    /// Output only. Whether the active query is enabled.
    public var activeQueryEnabled: Swift.Bool?

    /// Output only. Whether the index advisor is enabled.
    public var indexAdvisorEnabled: Swift.Bool?

    /// Output only. Whether the flag recommender is enabled.
    public var flagRecommenderEnabled: Swift.Bool?

    /// Initialize a new instance of `GeminiInstanceConfig`.
    public init(
      entitled: Swift.Bool? = nil,
      googleVacuumMgmtEnabled: Swift.Bool? = nil,
      oomSessionCancelEnabled: Swift.Bool? = nil,
      activeQueryEnabled: Swift.Bool? = nil,
      indexAdvisorEnabled: Swift.Bool? = nil,
      flagRecommenderEnabled: Swift.Bool? = nil,
    ) {
      self.entitled = entitled
      self.googleVacuumMgmtEnabled = googleVacuumMgmtEnabled
      self.oomSessionCancelEnabled = oomSessionCancelEnabled
      self.activeQueryEnabled = activeQueryEnabled
      self.indexAdvisorEnabled = indexAdvisorEnabled
      self.flagRecommenderEnabled = flagRecommenderEnabled
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.GeminiInstanceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
