// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BlueGreenDeploymentsService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleGax
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The response message for listing blue-green deployment resources.
  public struct ListBlueGreenDeploymentsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The list of blue-green deployment resources.
    public var blueGreenDeployments: [BlueGreenDeployment] = []

    /// A token to retrieve the next page of results, or empty if there are no
    /// more results.
    public var nextPageToken: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListBlueGreenDeploymentsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListBlueGreenDeploymentsResponse().with { $0.blueGreenDeployments = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let blueGreenDeployments = CodingKeys(stringValue: "blueGreenDeployments")
      static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

      static let _knownKeys: Set<Swift.String> = [
        "blueGreenDeployments",
        "nextPageToken",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [BlueGreenDeployment].self, forKey: .blueGreenDeployments)
      {
        self.blueGreenDeployments = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
        self.nextPageToken = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.blueGreenDeployments, forKey: .blueGreenDeployments)
      try container.encode(self.nextPageToken, forKey: .nextPageToken)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `ListBlueGreenDeploymentsResponse`: `"type.googleapis.com/google.cloud.sql.v1.ListBlueGreenDeploymentsResponse"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.ListBlueGreenDeploymentsResponse"
    }

    /// Initialize an instance of `ListBlueGreenDeploymentsResponse` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.sql.v1.ListBlueGreenDeploymentsResponse"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ListBlueGreenDeploymentsResponse` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  @_spi(GoogleCloudInternal)
  extension ListBlueGreenDeploymentsResponse: GoogleGax._PaginatedResponse {
    public func _getPaginatedItems() -> [BlueGreenDeployment] {
      return self.blueGreenDeployments
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
