// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Preferred location. This specifies where a Cloud SQL instance is located.
  /// Note that if the preferred location is not available, the instance will be
  /// located as close as possible within the region. Only one location may be
  /// specified.
  public struct LocationPreference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The App Engine application to follow, it must be in the same region as the
    /// Cloud SQL instance. WARNING: Changing this might restart the instance.
    public var followGaeApplication: Swift.String

    /// The preferred Compute Engine zone (for example: us-central1-a,
    /// us-central1-b, etc.). WARNING: Changing this might restart the instance.
    public var zone: Swift.String

    /// The preferred Compute Engine zone for the secondary/failover
    /// (for example: us-central1-a, us-central1-b, etc.).
    /// To disable this field, set it to 'no_secondary_zone'.
    public var secondaryZone: Swift.String

    /// This is always `sql#locationPreference`.
    public var kind: Swift.String

    /// Initialize a new instance of `LocationPreference`.
    public init(
      followGaeApplication: Swift.String = Swift.String(),
      zone: Swift.String = Swift.String(),
      secondaryZone: Swift.String = Swift.String(),
      kind: Swift.String = Swift.String(),
    ) {
      self.followGaeApplication = followGaeApplication
      self.zone = zone
      self.secondaryZone = secondaryZone
      self.kind = kind
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.LocationPreference"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
