// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Preferred location. This specifies where a Cloud SQL instance is located.
  /// Note that if the preferred location is not available, the instance will be
  /// located as close as possible within the region. Only one location may be
  /// specified.
  public struct LocationPreference: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The App Engine application to follow, it must be in the same region as the
    /// Cloud SQL instance. WARNING: Changing this might restart the instance.
    @available(*, deprecated)
    public var followGaeApplication: Swift.String = Swift.String()

    /// The preferred Compute Engine zone (for example: us-central1-a,
    /// us-central1-b, etc.). WARNING: Changing this might restart the instance.
    public var zone: Swift.String = Swift.String()

    /// The preferred Compute Engine zone for the secondary/failover
    /// (for example: us-central1-a, us-central1-b, etc.).
    /// To disable this field, set it to 'no_secondary_zone'.
    public var secondaryZone: Swift.String = Swift.String()

    /// This is always `sql#locationPreference`.
    public var kind: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LocationPreference`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocationPreference().with { $0.followGaeApplication = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let followGaeApplication = CodingKeys(stringValue: "followGaeApplication")
      static let zone = CodingKeys(stringValue: "zone")
      static let secondaryZone = CodingKeys(stringValue: "secondaryZone")
      static let kind = CodingKeys(stringValue: "kind")

      static let _knownKeys: Set<Swift.String> = [
        "followGaeApplication",
        "zone",
        "secondaryZone",
        "kind",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .followGaeApplication)
      {
        self.followGaeApplication = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
        self.zone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryZone) {
        self.secondaryZone = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
        self.kind = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.followGaeApplication, forKey: .followGaeApplication)
      try container.encode(self.zone, forKey: .zone)
      try container.encode(self.secondaryZone, forKey: .secondaryZone)
      try container.encode(self.kind, forKey: .kind)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.LocationPreference"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
