// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Maintenance window. This specifies when a Cloud SQL instance is
  /// restarted for system maintenance purposes.
  public struct MaintenanceWindow: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Hour of day - 0 to 23. Specify in the UTC time zone.
    public var hour: GoogleCloudWkt.Int32Value?

    /// Day of week - `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`,
    /// `SATURDAY`, or `SUNDAY`. Specify in the UTC time zone.
    /// Returned in output as an integer, 1 to 7, where `1` equals Monday.
    public var day: GoogleCloudWkt.Int32Value?

    /// Maintenance timing settings: `canary`, `stable`, or `week5`.
    /// For more information, see [About maintenance on Cloud SQL
    /// instances](https://cloud.google.com/sql/docs/mysql/maintenance).
    public var updateTrack: SqlUpdateTrack

    /// This is always `sql#maintenanceWindow`.
    public var kind: Swift.String

    /// Initialize a new instance of `MaintenanceWindow`.
    public init(
      hour: GoogleCloudWkt.Int32Value? = nil,
      day: GoogleCloudWkt.Int32Value? = nil,
      updateTrack: SqlUpdateTrack = SqlUpdateTrack(),
      kind: Swift.String = Swift.String(),
    ) {
      self.hour = hour
      self.day = day
      self.updateTrack = updateTrack
      self.kind = kind
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.MaintenanceWindow"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
