// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Read-replica configuration specific to MySQL databases.
  public struct MySqlReplicaConfiguration: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Path to a SQL dump file in Google Cloud Storage from which the replica
    /// instance is to be created. The URI is in the form gs://bucketName/fileName.
    /// Compressed gzip files (.gz) are also supported.
    /// Dumps have the binlog co-ordinates from which replication
    /// begins. This can be accomplished by setting --master-data to 1 when using
    /// mysqldump.
    public var dumpFilePath: Swift.String

    /// The username for the replication connection.
    public var username: Swift.String

    /// The password for the replication connection.
    public var password: Swift.String

    /// Seconds to wait between connect retries. MySQL's default is 60 seconds.
    public var connectRetryInterval: GoogleCloudWkt.Int32Value?

    /// Interval in milliseconds between replication heartbeats.
    public var masterHeartbeatPeriod: GoogleCloudWkt.Int64Value?

    /// PEM representation of the trusted CA's x509 certificate.
    public var caCertificate: Swift.String

    /// PEM representation of the replica's x509 certificate.
    public var clientCertificate: Swift.String

    /// PEM representation of the replica's private key. The corresponding public
    /// key is encoded in the client's certificate.
    public var clientKey: Swift.String

    /// A list of permissible ciphers to use for SSL encryption.
    public var sslCipher: Swift.String

    /// Whether or not to check the primary instance's Common Name value in the
    /// certificate that it sends during the SSL handshake.
    public var verifyServerCertificate: GoogleCloudWkt.BoolValue?

    /// This is always `sql#mysqlReplicaConfiguration`.
    public var kind: Swift.String

    /// Initialize a new instance of `MySqlReplicaConfiguration`.
    public init(
      dumpFilePath: Swift.String = Swift.String(),
      username: Swift.String = Swift.String(),
      password: Swift.String = Swift.String(),
      connectRetryInterval: GoogleCloudWkt.Int32Value? = nil,
      masterHeartbeatPeriod: GoogleCloudWkt.Int64Value? = nil,
      caCertificate: Swift.String = Swift.String(),
      clientCertificate: Swift.String = Swift.String(),
      clientKey: Swift.String = Swift.String(),
      sslCipher: Swift.String = Swift.String(),
      verifyServerCertificate: GoogleCloudWkt.BoolValue? = nil,
      kind: Swift.String = Swift.String(),
    ) {
      self.dumpFilePath = dumpFilePath
      self.username = username
      self.password = password
      self.connectRetryInterval = connectRetryInterval
      self.masterHeartbeatPeriod = masterHeartbeatPeriod
      self.caCertificate = caCertificate
      self.clientCertificate = clientCertificate
      self.clientKey = clientKey
      self.sslCipher = sslCipher
      self.verifyServerCertificate = verifyServerCertificate
      self.kind = kind
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.MySqlReplicaConfiguration"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
