// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Performance capture configuration.
  public struct PerformanceCaptureConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Enables or disables the performance capture feature.
    public var enabled: Swift.Bool?

    /// Optional. Specifies the interval in seconds between consecutive probes that
    /// check if any trigger condition thresholds have been reached.
    public var probingIntervalSeconds: Swift.Int32?

    /// Optional. Specifies the minimum number of consecutive probe threshold that
    /// triggers performance capture.
    public var probeThreshold: Swift.Int32?

    /// Optional. Specifies the minimum number of MySQL `Threads_running` to
    /// trigger the performance capture on the primary instance.
    public var runningThreadsThreshold: Swift.Int32?

    /// Optional. Specifies the minimum number of seconds replica must be lagging
    /// behind primary instance to trigger the performance capture on replica.
    public var secondsBehindSourceThreshold: Swift.Int32?

    /// Optional. Specifies the amount of time in seconds that a transaction needs
    /// to have been open before the watcher starts recording it.
    public var transactionDurationThreshold: Swift.Int32?

    /// Initialize a new instance of `PerformanceCaptureConfig`.
    public init(
      enabled: Swift.Bool? = nil,
      probingIntervalSeconds: Swift.Int32? = nil,
      probeThreshold: Swift.Int32? = nil,
      runningThreadsThreshold: Swift.Int32? = nil,
      secondsBehindSourceThreshold: Swift.Int32? = nil,
      transactionDurationThreshold: Swift.Int32? = nil,
    ) {
      self.enabled = enabled
      self.probingIntervalSeconds = probingIntervalSeconds
      self.probeThreshold = probeThreshold
      self.runningThreadsThreshold = runningThreadsThreshold
      self.secondsBehindSourceThreshold = secondsBehindSourceThreshold
      self.transactionDurationThreshold = transactionDurationThreshold
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.PerformanceCaptureConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
