// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService || SqlBackupsService || SqlDatabasesService || SqlInstancesService || SqlOperationsService || SqlSslCertsService || SqlUsersService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Pre-check major version upgrade context.
  public struct PreCheckMajorVersionUpgradeContext: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The target database version to upgrade to.
    public var targetDatabaseVersion: SqlDatabaseVersion = SqlDatabaseVersion()

    /// Output only. The responses from the precheck operation.
    public var preCheckResponse: [PreCheckResponse] = []

    /// Optional. This is always `sql#preCheckMajorVersionUpgradeContext`.
    public var kind: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PreCheckMajorVersionUpgradeContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PreCheckMajorVersionUpgradeContext().with { $0.targetDatabaseVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let targetDatabaseVersion = CodingKeys(stringValue: "targetDatabaseVersion")
      static let preCheckResponse = CodingKeys(stringValue: "preCheckResponse")
      static let kind = CodingKeys(stringValue: "kind")

      static let _knownKeys: Set<Swift.String> = [
        "targetDatabaseVersion",
        "preCheckResponse",
        "kind",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        SqlDatabaseVersion.self, forKey: .targetDatabaseVersion)
      {
        self.targetDatabaseVersion = value
      }
      if let value = try container.decodeIfPresent(
        [PreCheckResponse].self, forKey: .preCheckResponse)
      {
        self.preCheckResponse = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
        self.kind = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.targetDatabaseVersion, forKey: .targetDatabaseVersion)
      try container.encode(self.preCheckResponse, forKey: .preCheckResponse)
      try container.encode(self.kind, forKey: .kind)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.PreCheckMajorVersionUpgradeContext"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
