// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Settings for an automatically-setup Private Service Connect consumer endpoint
  /// that is used to connect to a Cloud SQL instance.
  public struct PscAutoConnectionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. This is the project ID of consumer service project of this
    /// consumer endpoint.
    ///
    /// Optional. This is only applicable if consumer_network is a shared vpc
    /// network.
    public var consumerProject: Swift.String

    /// Optional. The consumer network of this consumer endpoint. This must be a
    /// resource path that includes both the host project and the network name.
    ///
    /// For example, `projects/project1/global/networks/network1`.
    ///
    /// The consumer host project of this network might be different from the
    /// consumer service project.
    public var consumerNetwork: Swift.String

    /// The IP address of the consumer endpoint.
    public var ipAddress: Swift.String?

    /// The connection status of the consumer endpoint.
    public var status: Swift.String?

    /// The connection policy status of the consumer network.
    public var consumerNetworkStatus: Swift.String?

    /// Initialize a new instance of `PscAutoConnectionConfig`.
    public init(
      consumerProject: Swift.String = Swift.String(),
      consumerNetwork: Swift.String = Swift.String(),
      ipAddress: Swift.String? = nil,
      status: Swift.String? = nil,
      consumerNetworkStatus: Swift.String? = nil,
    ) {
      self.consumerProject = consumerProject
      self.consumerNetwork = consumerNetwork
      self.ipAddress = ipAddress
      self.status = status
      self.consumerNetworkStatus = consumerNetworkStatus
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.PscAutoConnectionConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
