// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The read pool auto-scale configuration.
  public struct ReadPoolAutoScaleConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether read pool auto scaling is enabled.
    public var enabled: Swift.Bool? = nil

    /// Minimum number of read pool nodes to be maintained.
    public var minNodeCount: Swift.Int32? = nil

    /// Maximum number of read pool nodes to be maintained.
    public var maxNodeCount: Swift.Int32? = nil

    /// Optional. Target metrics for read pool auto scaling.
    public var targetMetrics: [ReadPoolAutoScaleConfig.TargetMetric] = []

    /// Indicates whether read pool auto scaling supports scale in operations
    /// (removing nodes).
    public var disableScaleIn: Swift.Bool? = nil

    /// The cooldown period for scale-in operations.
    public var scaleInCooldownSeconds: Swift.Int32? = nil

    /// The cooldown period for scale-out operations.
    public var scaleOutCooldownSeconds: Swift.Int32? = nil

    /// Initialize a new instance of `ReadPoolAutoScaleConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReadPoolAutoScaleConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Target metric for read pool auto scaling.
    public struct TargetMetric: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The metric name to be used for auto scaling.
      public var metric: Swift.String? = nil

      /// The target value for the metric.
      public var targetValue: Swift.Float? = nil

      /// Initialize a new instance of `TargetMetric`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TargetMetric().with { $0.metric = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.sql.v1.ReadPoolAutoScaleConfig.TargetMetric"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.ReadPoolAutoScaleConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
