// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// A primary instance and disaster recovery (DR) replica pair.
  /// A DR replica is a cross-region replica that you designate for failover in
  /// the event that the primary instance experiences regional failure.
  /// Applicable to MySQL and PostgreSQL.
  public struct ReplicationCluster: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. If set, this field indicates this instance has a private
    /// service access (PSA) DNS endpoint that is pointing to the primary instance
    /// of the cluster. If this instance is the primary, then the DNS endpoint
    /// points to this instance. After a switchover or replica failover operation,
    /// this DNS endpoint points to the promoted instance. This is a read-only
    /// field, returned to the user as information. This field can exist even if a
    /// standalone instance doesn't have a DR replica yet or the DR replica is
    /// deleted.
    public var psaWriteEndpoint: Swift.String = Swift.String()

    /// Optional. If the instance is a primary instance, then this field identifies
    /// the disaster recovery (DR) replica. A DR replica is an optional
    /// configuration for Enterprise Plus edition instances. If the instance is a
    /// read replica, then the field is not set. Set this field to a replica name
    /// to designate a DR replica for a primary instance. Remove the replica name
    /// to remove the DR replica designation.
    public var failoverDrReplicaName: Swift.String = Swift.String()

    /// Output only. Read-only field that indicates whether the replica is a DR
    /// replica. This field is not set if the instance is a primary instance.
    public var drReplica: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReplicationCluster`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReplicationCluster().with { $0.psaWriteEndpoint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let psaWriteEndpoint = CodingKeys(stringValue: "psaWriteEndpoint")
      static let failoverDrReplicaName = CodingKeys(stringValue: "failoverDrReplicaName")
      static let drReplica = CodingKeys(stringValue: "drReplica")

      static let _knownKeys: Set<Swift.String> = [
        "psaWriteEndpoint",
        "failoverDrReplicaName",
        "drReplica",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .psaWriteEndpoint) {
        self.psaWriteEndpoint = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .failoverDrReplicaName)
      {
        self.failoverDrReplicaName = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .drReplica) {
        self.drReplica = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.psaWriteEndpoint, forKey: .psaWriteEndpoint)
      try container.encode(self.failoverDrReplicaName, forKey: .failoverDrReplicaName)
      try container.encode(self.drReplica, forKey: .drReplica)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.ReplicationCluster"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
