// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation
  import GoogleCloudWkt

  /// Database instance settings.
  public struct Settings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The version of instance settings. This is a required field for update
    /// method to make sure concurrent updates are handled properly. During update,
    /// use the most recent settingsVersion value for this instance and do not try
    /// to update this value.
    public var settingsVersion: GoogleCloudWkt.Int64Value? = nil

    /// The App Engine app IDs that can access this instance.
    /// (Deprecated) Applied to First Generation instances only.
    @available(*, deprecated)
    public var authorizedGaeApplications: [Swift.String] = []

    /// The tier (or machine type) for this instance, for example
    /// `db-custom-1-3840`. WARNING: Changing this restarts the instance.
    public var tier: Swift.String = Swift.String()

    /// This is always `sql#settings`.
    public var kind: Swift.String = Swift.String()

    /// User-provided labels, represented as a dictionary where each label is a
    /// single key value pair.
    public var userLabels: [Swift.String: Swift.String] = [:]

    /// Availability type. Potential values:
    /// *  `ZONAL`: The instance serves data from only one zone. Outages in that
    /// zone affect data accessibility.
    /// *  `REGIONAL`: The instance can serve data from more than one zone in a
    /// region (it is highly available)./
    ///
    /// For more information, see [Overview of the High Availability
    /// Configuration](https://cloud.google.com/sql/docs/mysql/high-availability).
    public var availabilityType: SqlAvailabilityType = SqlAvailabilityType()

    /// The pricing plan for this instance. This can be either `PER_USE` or
    /// `PACKAGE`. Only `PER_USE` is supported for Second Generation instances.
    public var pricingPlan: SqlPricingPlan = SqlPricingPlan()

    /// The type of replication this instance uses. This can be either
    /// `ASYNCHRONOUS` or `SYNCHRONOUS`. (Deprecated) This property was only
    /// applicable to First Generation instances.
    @available(*, deprecated)
    public var replicationType: SqlReplicationType = SqlReplicationType()

    /// The maximum size to which storage capacity can be automatically increased.
    /// The default value is 0, which specifies that there is no limit.
    public var storageAutoResizeLimit: GoogleCloudWkt.Int64Value? = nil

    /// The activation policy specifies when the instance is activated; it is
    /// applicable only when the instance state is RUNNABLE. Valid values:
    /// *  `ALWAYS`: The instance is on, and remains so even in the absence of
    /// connection requests.
    /// *  `NEVER`: The instance is off; it is not activated, even if a
    /// connection request arrives.
    public var activationPolicy: Settings.SqlActivationPolicy = Settings.SqlActivationPolicy()

    /// The settings for IP Management. This allows to enable or disable the
    /// instance IP and manage which external networks can connect to the instance.
    /// The IPv4 address cannot be disabled for Second Generation instances.
    public var ipConfiguration: IpConfiguration? = nil

    /// Configuration to increase storage size automatically. The default value is
    /// true.
    public var storageAutoResize: GoogleCloudWkt.BoolValue? = nil

    /// The location preference settings. This allows the instance to be located as
    /// near as possible to either an App Engine app or Compute Engine zone for
    /// better performance. App Engine co-location was only applicable to First
    /// Generation instances.
    public var locationPreference: LocationPreference? = nil

    /// The database flags passed to the instance at startup.
    public var databaseFlags: [DatabaseFlags] = []

    /// The type of data disk: `PD_SSD` (default) or `PD_HDD`. Not used for
    /// First Generation instances.
    public var dataDiskType: SqlDataDiskType = SqlDataDiskType()

    /// The maintenance window for this instance. This specifies when the instance
    /// can be restarted for maintenance purposes.
    public var maintenanceWindow: MaintenanceWindow? = nil

    /// The daily backup configuration for the instance.
    public var backupConfiguration: BackupConfiguration? = nil

    /// Configuration specific to read replica instances. Indicates whether
    /// replication is enabled or not. WARNING: Changing this restarts the
    /// instance.
    public var databaseReplicationEnabled: GoogleCloudWkt.BoolValue? = nil

    /// Configuration specific to read replica instances. Indicates whether
    /// database flags for crash-safe replication are enabled. This property was
    /// only applicable to First Generation instances.
    @available(*, deprecated)
    public var crashSafeReplicationEnabled: GoogleCloudWkt.BoolValue? = nil

    /// The size of data disk, in GB. The data disk size minimum is 10GB.
    public var dataDiskSizeGb: GoogleCloudWkt.Int64Value? = nil

    /// Active Directory configuration, relevant only for Cloud SQL for SQL Server.
    public var activeDirectoryConfig: SqlActiveDirectoryConfig? = nil

    /// The name of server Instance collation.
    public var collation: Swift.String = Swift.String()

    /// Deny maintenance periods
    public var denyMaintenancePeriods: [DenyMaintenancePeriod] = []

    /// Insights configuration, for now relevant only for Postgres.
    public var insightsConfig: InsightsConfig? = nil

    /// The local user password validation policy of the instance.
    public var passwordValidationPolicy: PasswordValidationPolicy? = nil

    /// SQL Server specific audit configuration.
    public var sqlServerAuditConfig: SqlServerAuditConfig? = nil

    /// Optional. The edition type of the Cloud SQL instance.
    public var edition: Settings.Edition = Settings.Edition()

    /// Specifies if connections must use Cloud SQL connectors.
    /// Option values include the following: `NOT_REQUIRED` (Cloud SQL instances
    /// can be connected without Cloud SQL
    /// Connectors) and `REQUIRED` (Only allow connections that use Cloud SQL
    /// Connectors).
    ///
    /// Note that using REQUIRED disables all existing authorized networks. If
    /// this field is not specified when creating a new instance, NOT_REQUIRED is
    /// used. If this field is not specified when patching or updating an existing
    /// instance, it is left unchanged in the instance.
    public var connectorEnforcement: Settings.ConnectorEnforcement = Settings.ConnectorEnforcement()

    /// Configuration to protect against accidental instance deletion.
    public var deletionProtectionEnabled: GoogleCloudWkt.BoolValue? = nil

    /// Server timezone, relevant only for Cloud SQL for SQL Server.
    public var timeZone: Swift.String = Swift.String()

    /// Specifies advanced machine configuration for the instances relevant only
    /// for SQL Server.
    public var advancedMachineFeatures: AdvancedMachineFeatures? = nil

    /// Configuration for data cache.
    public var dataCacheConfig: DataCacheConfig? = nil

    /// Optional. Configuration value for recreation of replica after certain
    /// replication lag
    public var replicationLagMaxSeconds: GoogleCloudWkt.Int32Value? = nil

    /// Optional. When this parameter is set to true, Cloud SQL instances can
    /// connect to Vertex AI to pass requests for real-time predictions and
    /// insights to the AI. The default value is false. This applies only to Cloud
    /// SQL for MySQL and Cloud SQL for PostgreSQL instances.
    public var enableGoogleMlIntegration: GoogleCloudWkt.BoolValue? = nil

    /// Optional. By default, Cloud SQL instances have schema extraction disabled
    /// for Dataplex. When this parameter is set to true, schema extraction for
    /// Dataplex on Cloud SQL instances is activated.
    public var enableDataplexIntegration: GoogleCloudWkt.BoolValue? = nil

    /// Optional. When this parameter is set to true, Cloud SQL retains backups of
    /// the instance even after the instance is deleted. The ON_DEMAND backup will
    /// be retained until customer deletes the backup or the project. The AUTOMATED
    /// backup will be retained based on the backups retention setting.
    public var retainBackupsOnDelete: GoogleCloudWkt.BoolValue? = nil

    /// Optional. Provisioned number of I/O operations per second for the data
    /// disk. This field is only used for hyperdisk-balanced disk types.
    public var dataDiskProvisionedIops: Swift.Int64? = nil

    /// Optional. Provisioned throughput measured in MiB per second for the data
    /// disk. This field is only used for hyperdisk-balanced disk types.
    public var dataDiskProvisionedThroughput: Swift.Int64? = nil

    /// Optional. The managed connection pooling configuration for the instance.
    public var connectionPoolConfig: ConnectionPoolConfig? = nil

    /// Optional. The final backup configuration for the instance.
    public var finalBackupConfig: FinalBackupConfig? = nil

    /// Optional. The read pool auto-scale configuration for the instance.
    public var readPoolAutoScaleConfig: ReadPoolAutoScaleConfig? = nil

    /// Optional. Whether the replica is in accelerated mode. This feature is in
    /// private preview and requires allowlisting to take effect.
    public var acceleratedReplicaMode: GoogleCloudWkt.BoolValue? = nil

    /// Optional. Cloud SQL for MySQL auto-upgrade configuration. When this
    /// parameter is set to true, auto-upgrade is enabled for MySQL 8.0 minor
    /// versions. The MySQL version must be 8.0.35 or higher.
    public var autoUpgradeEnabled: Swift.Bool? = nil

    /// Optional. The Microsoft Entra ID configuration for the SQL Server instance.
    public var entraidConfig: SqlServerEntraIdConfig? = nil

    /// This parameter controls whether to allow using ExecuteSql API to connect to
    /// the instance. Not allowed by default.
    public var dataApiAccess: Settings.DataApiAccess? = nil

    /// Optional. Configuration for Performance Capture, provides diagnostic
    /// metrics during high load situations.
    public var performanceCaptureConfig: PerformanceCaptureConfig? = nil

    /// Initialize a new instance of `Settings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Settings().with { $0.settingsVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Specifies when the instance is activated.
    public enum SqlActivationPolicy: Codable, Equatable, Sendable {
      /// Unknown activation plan.
      case unspecified
      /// The instance is always up and running.
      case always
      /// The instance never starts.
      case never
      /// The instance starts upon receiving requests.
      @available(*, deprecated)
      case onDemand
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .always: return 1
        case .never: return 2
        case .onDemand: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SQL_ACTIVATION_POLICY_UNSPECIFIED"
        case .always: return "ALWAYS"
        case .never: return "NEVER"
        case .onDemand: return "ON_DEMAND"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SQL_ACTIVATION_POLICY_UNSPECIFIED": self = .unspecified
        case "ALWAYS": self = .always
        case "NEVER": self = .never
        case "ON_DEMAND": self = .onDemand
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .always
        case 2: self = .never
        case 3: self = .onDemand
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .always: return try container.encode(1)
        case .never: return try container.encode(2)
        case .onDemand: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The list of Cloud SQL editions available to users.
    public enum Edition: Codable, Equatable, Sendable {
      /// The instance did not specify the edition.
      case unspecified
      /// The instance is an enterprise edition.
      case enterprise
      /// The instance is an Enterprise Plus edition.
      case enterprisePlus
      /// This instance is a Cloud SQL developer edition instance.
      case developer
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .enterprise: return 2
        case .enterprisePlus: return 3
        case .developer: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "EDITION_UNSPECIFIED"
        case .enterprise: return "ENTERPRISE"
        case .enterprisePlus: return "ENTERPRISE_PLUS"
        case .developer: return "DEVELOPER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "EDITION_UNSPECIFIED": self = .unspecified
        case "ENTERPRISE": self = .enterprise
        case "ENTERPRISE_PLUS": self = .enterprisePlus
        case "DEVELOPER": self = .developer
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 2: self = .enterprise
        case 3: self = .enterprisePlus
        case 5: self = .developer
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .enterprise: return try container.encode(2)
        case .enterprisePlus: return try container.encode(3)
        case .developer: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The options for enforcing Cloud SQL connectors in the instance.
    public enum ConnectorEnforcement: Codable, Equatable, Sendable {
      /// The requirement for Cloud SQL connectors is unknown.
      case unspecified
      /// Do not require Cloud SQL connectors.
      case notRequired
      /// Require all connections to use Cloud SQL connectors, including the
      /// Cloud SQL Auth Proxy and Cloud SQL Java, Python, and Go connectors.
      /// Note: This disables all existing authorized networks.
      case `required`
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .notRequired: return 1
        case .`required`: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONNECTOR_ENFORCEMENT_UNSPECIFIED"
        case .notRequired: return "NOT_REQUIRED"
        case .`required`: return "REQUIRED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONNECTOR_ENFORCEMENT_UNSPECIFIED": self = .unspecified
        case "NOT_REQUIRED": self = .notRequired
        case "REQUIRED": self = .`required`
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .notRequired
        case 2: self = .`required`
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .notRequired: return try container.encode(1)
        case .`required`: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// ExecuteSql API's access to the instance.
    public enum DataApiAccess: Codable, Equatable, Sendable {
      /// Unspecified, effectively the same as `DISALLOW_DATA_API`.
      case unspecified
      /// Disallow using ExecuteSql API to connect to the instance.
      case disallowDataApi
      /// Allow using ExecuteSql API to connect to the instance. For private IP
      /// instances, this allows authorized users to access the instance from
      /// the public internet using ExecuteSql API.
      case allowDataApi
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .disallowDataApi: return 1
        case .allowDataApi: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DATA_API_ACCESS_UNSPECIFIED"
        case .disallowDataApi: return "DISALLOW_DATA_API"
        case .allowDataApi: return "ALLOW_DATA_API"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DATA_API_ACCESS_UNSPECIFIED": self = .unspecified
        case "DISALLOW_DATA_API": self = .disallowDataApi
        case "ALLOW_DATA_API": self = .allowDataApi
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .disallowDataApi
        case 2: self = .allowDataApi
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .disallowDataApi: return try container.encode(1)
        case .allowDataApi: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.Settings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
