// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService
  import Foundation

  /// The status of a backup run.
  public enum SqlBackupRunStatus: Codable, Equatable, Sendable {
    /// The status of the run is unknown.
    case unspecified
    /// The backup operation was enqueued.
    case enqueued
    /// The backup is overdue across a given backup window. Indicates a
    /// problem. Example: Long-running operation in progress during
    /// the whole window.
    case overdue
    /// The backup is in progress.
    case running
    /// The backup failed.
    case failed
    /// The backup was successful.
    case successful
    /// The backup was skipped (without problems) for a given backup
    /// window. Example: Instance was idle.
    case skipped
    /// The backup is about to be deleted.
    case deletionPending
    /// The backup deletion failed.
    case deletionFailed
    /// The backup has been deleted.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enqueued: return 1
      case .overdue: return 2
      case .running: return 3
      case .failed: return 4
      case .successful: return 5
      case .skipped: return 6
      case .deletionPending: return 7
      case .deletionFailed: return 8
      case .deleted: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SQL_BACKUP_RUN_STATUS_UNSPECIFIED"
      case .enqueued: return "ENQUEUED"
      case .overdue: return "OVERDUE"
      case .running: return "RUNNING"
      case .failed: return "FAILED"
      case .successful: return "SUCCESSFUL"
      case .skipped: return "SKIPPED"
      case .deletionPending: return "DELETION_PENDING"
      case .deletionFailed: return "DELETION_FAILED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SQL_BACKUP_RUN_STATUS_UNSPECIFIED": self = .unspecified
      case "ENQUEUED": self = .enqueued
      case "OVERDUE": self = .overdue
      case "RUNNING": self = .running
      case "FAILED": self = .failed
      case "SUCCESSFUL": self = .successful
      case "SKIPPED": self = .skipped
      case "DELETION_PENDING": self = .deletionPending
      case "DELETION_FAILED": self = .deletionFailed
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enqueued
      case 2: self = .overdue
      case 3: self = .running
      case 4: self = .failed
      case 5: self = .successful
      case 6: self = .skipped
      case 7: self = .deletionPending
      case 8: self = .deletionFailed
      case 9: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enqueued: return try container.encode(1)
      case .overdue: return try container.encode(2)
      case .running: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .successful: return try container.encode(5)
      case .skipped: return try container.encode(6)
      case .deletionPending: return try container.encode(7)
      case .deletionFailed: return try container.encode(8)
      case .deleted: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }
#endif
