// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  ///
  /// @Snippet(path: "SqlBackupsServiceQuickstart")
  public final class SqlBackupsServiceClient: Clients.SqlBackupsServiceProtocol, Sendable {
    let inner: any Clients.SqlBackupsServiceStub

    /// Creates a new `SqlBackupsServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlBackupsServiceStub = try Clients.SqlBackupsServiceTransport(options)
      inner = Clients.SqlBackupsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlBackupsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Creates a backup for a Cloud SQL instance. This API can be used only to
    /// create on-demand backups.
    ///
    /// @Snippet(path: "SqlBackupsService_CreateBackup")
    public func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.createBackup(request: request, options: options)
    }

    /// Retrieves a resource containing information about a backup.
    ///
    /// @Snippet(path: "SqlBackupsService_GetBackup")
    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Backup {
      try await self.inner.getBackup(request: request, options: options)
    }

    /// Lists all backups associated with the project.
    ///
    /// @Snippet(path: "SqlBackupsService_ListBackups")
    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ListBackupsResponse {
      try await self.inner.listBackups(request: request, options: options)
    }

    /// Lists all backups associated with the project.
    ///
    /// @Snippet(path: "SqlBackupsService_ListBackups")
    public func listBackups(
      byItem: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Backup, Swift.Error> {
      let listRpc = { (token: Swift.String) async throws -> GoogleCloudSqlV1.ListBackupsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listBackups(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Updates the retention period and description of the backup. You can use
    /// this API to update final backups only.
    ///
    /// @Snippet(path: "SqlBackupsService_UpdateBackup")
    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.updateBackup(request: request, options: options)
    }

    /// Deletes the backup.
    ///
    /// @Snippet(path: "SqlBackupsService_DeleteBackup")
    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.deleteBackup(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlBackupsServiceClient`.
    ///
    /// To mock `SqlBackupsServiceClient` change your functions to receive
    /// `some SqlBackupsServiceProtocol` or `any SqlBackupsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlBackupsServiceProtocol {
      /// See `SqlBackupsServiceClient.createBackup`.
      func createBackup(request: CreateBackupRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.createBackup`.
      func createBackup(
        parent: Swift.String,
        backup: Backup?,
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.getBackup`.
      func getBackup(request: GetBackupRequest) async throws -> GoogleCloudSqlV1.Backup

      /// See `SqlBackupsServiceClient.getBackup`.
      func getBackup(
        name: Swift.String,
      ) async throws -> GoogleCloudSqlV1.Backup

      /// See `SqlBackupsServiceClient.listBackups`.
      func listBackups(request: ListBackupsRequest) async throws
        -> GoogleCloudSqlV1.ListBackupsResponse

      /// See `SqlBackupsServiceClient.listBackups`.
      func listBackups(
        byItem: ListBackupsRequest
      ) -> any AsyncSequence<Backup, Swift.Error>

      /// See `SqlBackupsServiceClient.listBackups`.
      func listBackups(
        parent: Swift.String,
      ) -> any AsyncSequence<Backup, Swift.Error>

      /// See `SqlBackupsServiceClient.updateBackup`.
      func updateBackup(request: UpdateBackupRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.updateBackup`.
      func updateBackup(
        backup: Backup?,
        updateMask: GoogleWKT.FieldMask?,
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.deleteBackup`.
      func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.deleteBackup`.
      func deleteBackup(
        name: Swift.String,
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.createBackup`.
      func createBackup(
        request: CreateBackupRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.getBackup`.
      func getBackup(
        request: GetBackupRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Backup

      /// See `SqlBackupsServiceClient.listBackups`.
      func listBackups(
        request: ListBackupsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ListBackupsResponse

      /// See `SqlBackupsServiceClient.listBackups`.
      func listBackups(
        byItem: ListBackupsRequest, options: GoogleGax.RequestOptions
      ) -> any AsyncSequence<Backup, Swift.Error>

      /// See `SqlBackupsServiceClient.updateBackup`.
      func updateBackup(
        request: UpdateBackupRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupsServiceClient.deleteBackup`.
      func deleteBackup(
        request: DeleteBackupRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation
    }
  }

  // Default implementations
  extension Clients.SqlBackupsServiceProtocol {
    public func createBackup(request: CreateBackupRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.createBackup(request: request, options: .init())
    }

    public func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createBackup(
      parent: Swift.String,
      backup: Backup?,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = CreateBackupRequest().with {
        $0.parent = parent
        $0.backup = backup
      }
      return try await self.createBackup(request: request)
    }

    public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudSqlV1.Backup {
      try await self.getBackup(request: request, options: .init())
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Backup {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getBackup(
      name: Swift.String,
    ) async throws -> GoogleCloudSqlV1.Backup {
      let request = GetBackupRequest().with {
        $0.name = name
      }
      return try await self.getBackup(request: request)
    }

    public func listBackups(request: ListBackupsRequest) async throws
      -> GoogleCloudSqlV1.ListBackupsResponse
    {
      try await self.listBackups(request: request, options: .init())
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ListBackupsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listBackups(
      byItem: ListBackupsRequest
    ) -> any AsyncSequence<Backup, Swift.Error> {
      self.listBackups(byItem: byItem, options: .init())
    }

    public func listBackups(
      byItem: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Backup, Swift.Error> {
      let listRpc = { (token: Swift.String) async throws -> GoogleCloudSqlV1.ListBackupsResponse in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listBackups(
      parent: Swift.String,
    ) -> any AsyncSequence<Backup, Swift.Error> {
      let request = ListBackupsRequest().with {
        $0.parent = parent
      }
      return self.listBackups(byItem: request)
    }

    public func updateBackup(request: UpdateBackupRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.updateBackup(request: request, options: .init())
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateBackup(
      backup: Backup?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = UpdateBackupRequest().with {
        $0.backup = backup
        $0.updateMask = updateMask
      }
      return try await self.updateBackup(request: request)
    }

    public func deleteBackup(request: DeleteBackupRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.deleteBackup(request: request, options: .init())
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteBackup(
      name: Swift.String,
    ) async throws -> GoogleCloudSqlV1.Operation {
      let request = DeleteBackupRequest().with {
        $0.name = name
      }
      return try await self.deleteBackup(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'SqlBackupsService' trait in Package.swift to use this client."
  )
  public final class SqlBackupsServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'SqlBackupsService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
