// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService
  import Foundation
  import GoogleCloudWkt

  /// Backup runs delete request.
  public struct SqlBackupRunsDeleteRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The ID of the backup run to delete. To find a backup run ID, use the
    /// [list](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/backupRuns/list)
    /// method.
    public var id: Swift.Int64

    /// Cloud SQL instance ID. This does not include the project ID.
    public var instance: Swift.String

    /// Project ID of the project that contains the instance.
    public var project: Swift.String

    /// Initialize a new instance of `SqlBackupRunsDeleteRequest`.
    public init(
      id: Swift.Int64 = Swift.Int64(),
      instance: Swift.String = Swift.String(),
      project: Swift.String = Swift.String(),
    ) {
      self.id = id
      self.instance = instance
      self.project = project
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlBackupRunsDeleteRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
