// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWKT
  import GoogleCloudGax

  /// Service for managing database backups.
  ///
  /// @Snippet(path: "SqlBackupRunsServiceQuickstart")
  public final class SqlBackupRunsServiceClient: Clients.SqlBackupRunsServiceProtocol, Sendable {
    let inner: any Clients.SqlBackupRunsServiceStub

    /// Creates a new `SqlBackupRunsServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlBackupRunsServiceStub = try Clients.SqlBackupRunsServiceTransport(
        options)
      inner = Clients.SqlBackupRunsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlBackupRunsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Deletes the backup taken by a backup run.
    ///
    /// @Snippet(path: "SqlBackupRunsService_Delete")
    public func delete(
      request: SqlBackupRunsDeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.delete(request: request, options: options)
    }

    /// Retrieves a resource containing information about a backup run.
    ///
    /// @Snippet(path: "SqlBackupRunsService_Get")
    public func `get`(
      request: SqlBackupRunsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BackupRun {
      try await self.inner.`get`(request: request, options: options)
    }

    /// Creates a new backup run on demand.
    ///
    /// @Snippet(path: "SqlBackupRunsService_Insert")
    public func insert(
      request: SqlBackupRunsInsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.insert(request: request, options: options)
    }

    /// Lists all backup runs associated with the project or a given instance
    /// and configuration in the reverse chronological order of the backup
    /// initiation time.
    ///
    /// @Snippet(path: "SqlBackupRunsService_List")
    public func list(
      request: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BackupRunsListResponse {
      try await self.inner.list(request: request, options: options)
    }

    /// Lists all backup runs associated with the project or a given instance
    /// and configuration in the reverse chronological order of the backup
    /// initiation time.
    ///
    /// @Snippet(path: "SqlBackupRunsService_List")
    public func list(
      byItem: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<BackupRun, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudSqlV1.BackupRunsListResponse in
        var request = byItem
        request.pageToken = token
        return try await self.list(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlBackupRunsServiceClient`.
    ///
    /// To mock `SqlBackupRunsServiceClient` change your functions to receive
    /// `some SqlBackupRunsServiceProtocol` or `any SqlBackupRunsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlBackupRunsServiceProtocol {
      /// See `SqlBackupRunsServiceClient.delete`.
      func delete(request: SqlBackupRunsDeleteRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupRunsServiceClient.`get``.
      func `get`(request: SqlBackupRunsGetRequest) async throws -> GoogleCloudSqlV1.BackupRun

      /// See `SqlBackupRunsServiceClient.insert`.
      func insert(request: SqlBackupRunsInsertRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupRunsServiceClient.list`.
      func list(request: SqlBackupRunsListRequest) async throws
        -> GoogleCloudSqlV1.BackupRunsListResponse

      /// See `SqlBackupRunsServiceClient.list`.
      func list(
        byItem: SqlBackupRunsListRequest
      ) throws -> any AsyncSequence<BackupRun, Swift.Error>

      /// See `SqlBackupRunsServiceClient.delete`.
      func delete(
        request: SqlBackupRunsDeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupRunsServiceClient.`get``.
      func `get`(
        request: SqlBackupRunsGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.BackupRun

      /// See `SqlBackupRunsServiceClient.insert`.
      func insert(
        request: SqlBackupRunsInsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlBackupRunsServiceClient.list`.
      func list(
        request: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.BackupRunsListResponse

      /// See `SqlBackupRunsServiceClient.list`.
      func list(
        byItem: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<BackupRun, Swift.Error>
    }
  }

  // Default implementations
  extension Clients.SqlBackupRunsServiceProtocol {
    public func delete(request: SqlBackupRunsDeleteRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: SqlBackupRunsDeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(request: SqlBackupRunsGetRequest) async throws -> GoogleCloudSqlV1.BackupRun {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: SqlBackupRunsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BackupRun {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(request: SqlBackupRunsInsertRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: SqlBackupRunsInsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(request: SqlBackupRunsListRequest) async throws
      -> GoogleCloudSqlV1.BackupRunsListResponse
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.BackupRunsListResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: SqlBackupRunsListRequest
    ) throws -> any AsyncSequence<BackupRun, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: SqlBackupRunsListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<BackupRun, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudSqlV1.BackupRunsListResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }
  }
#endif
