// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlConnectService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleCloudGax

  extension Clients {
    protocol SqlConnectServiceStub {
      func getConnectSettings(
        request: GetConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ConnectSettings

      func resolveConnectSettings(
        request: ResolveConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ConnectSettings

      func generateEphemeralCert(
        request: GenerateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.GenerateEphemeralCertResponse
    }

    class SqlConnectServiceTransport: SqlConnectServiceStub {
      let inner: GoogleCloudGax.HTTPClient

      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        self.inner = try GoogleCloudGax.HTTPClient(
          from: options, withDefaultEndpoint: "https://sqladmin.googleapis.com")
      }

      public func getConnectSettings(
        request: GetConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ConnectSettings {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.project as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.project' is not set or is empty")
          }
          guard let pathVariable1 = request.instance as Swift.String?, !pathVariable1.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.instance' is not set or is empty")
          }
          return "/v1/projects/\(pathVariable0)/instances/\(pathVariable1)/connectSettings"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.readTime, prefix: "readTime"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudSqlV1.ConnectSettings.self, from: data)
      }

      public func resolveConnectSettings(
        request: ResolveConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ConnectSettings {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.location as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.location' is not set or is empty")
          }
          guard let pathVariable1 = request.dnsName as Swift.String?, !pathVariable1.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.dns_name' is not set or is empty")
          }
          return "/v1/locations/\(pathVariable0)/dns/\(pathVariable1):resolveConnectSettings"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudSqlV1.ConnectSettings.self, from: data)
      }

      public func generateEphemeralCert(
        request: GenerateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.GenerateEphemeralCertResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.project as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.project' is not set or is empty")
          }
          guard let pathVariable1 = request.instance as Swift.String?, !pathVariable1.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.instance' is not set or is empty")
          }
          return "/v1/projects/\(pathVariable0)/instances/\(pathVariable1):generateEphemeralCert"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(request)
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudSqlV1.GenerateEphemeralCertResponse.self, from: data)
      }
    }
  }
#endif
