// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlConnectService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Cloud SQL connect service.
  ///
  /// @Snippet(path: "SqlConnectServiceQuickstart")
  public protocol SqlConnectService {
    /// Retrieves connect settings about a Cloud SQL instance.
    ///
    /// @Snippet(path: "SqlConnectService_GetConnectSettings")
    func getConnectSettings(request: GetConnectSettingsRequest) async throws
      -> GoogleCloudSqlV1.ConnectSettings

    /// Generates a short-lived X509 certificate containing the provided public key
    /// and signed by a private key specific to the target instance. Users may use
    /// the certificate to authenticate as themselves when connecting to the
    /// database.
    ///
    /// @Snippet(path: "SqlConnectService_GenerateEphemeralCert")
    func generateEphemeralCert(request: GenerateEphemeralCertRequest) async throws
      -> GoogleCloudSqlV1.GenerateEphemeralCertResponse

    /// Retrieves connect settings about a Cloud SQL instance.
    ///
    /// @Snippet(path: "SqlConnectService_GetConnectSettings")
    func getConnectSettings(
      request: GetConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ConnectSettings

    /// Generates a short-lived X509 certificate containing the provided public key
    /// and signed by a private key specific to the target instance. Users may use
    /// the certificate to authenticate as themselves when connecting to the
    /// database.
    ///
    /// @Snippet(path: "SqlConnectService_GenerateEphemeralCert")
    func generateEphemeralCert(
      request: GenerateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.GenerateEphemeralCertResponse
  }

  extension Clients {
    /// The recommended implementation for ``SqlConnectService``.
    public class SqlConnectServiceClient: SqlConnectService {
      let inner: any SqlConnectServiceStub

      /// Creates a new `SqlConnectServiceClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any SqlConnectServiceStub = try SqlConnectServiceTransport(options)
        inner = SqlConnectServiceRetry(inner, options: options)
        if let logger = options.logger {
          inner = SqlConnectServiceLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `SqlConnectService.getConnectSettings`
      public func getConnectSettings(
        request: GetConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.ConnectSettings {
        try await self.inner.getConnectSettings(request: request, options: options)
      }

      /// See `SqlConnectService.generateEphemeralCert`
      public func generateEphemeralCert(
        request: GenerateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.GenerateEphemeralCertResponse {
        try await self.inner.generateEphemeralCert(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension SqlConnectService {
    public func getConnectSettings(request: GetConnectSettingsRequest) async throws
      -> GoogleCloudSqlV1.ConnectSettings
    {
      try await self.getConnectSettings(request: request, options: .init())
    }

    public func getConnectSettings(
      request: GetConnectSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.ConnectSettings {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func generateEphemeralCert(request: GenerateEphemeralCertRequest) async throws
      -> GoogleCloudSqlV1.GenerateEphemeralCertResponse
    {
      try await self.generateEphemeralCert(request: request, options: .init())
    }

    public func generateEphemeralCert(
      request: GenerateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.GenerateEphemeralCertResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }
  }
#endif
