// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation

  /// The type of disk that is used for a v2 instance to use.
  public enum SqlDataDiskType: Codable, Equatable, Sendable {
    /// This is an unknown data disk type.
    case unspecified
    /// An SSD data disk.
    case pdSsd
    /// An HDD data disk.
    case pdHdd
    /// This field is deprecated and will be removed from a future version of the
    /// API.
    @available(*, deprecated)
    case obsoleteLocalSsd
    /// A Hyperdisk Balanced data disk.
    case hyperdiskBalanced
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pdSsd: return 1
      case .pdHdd: return 2
      case .obsoleteLocalSsd: return 3
      case .hyperdiskBalanced: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "SQL_DATA_DISK_TYPE_UNSPECIFIED"
      case .pdSsd: return "PD_SSD"
      case .pdHdd: return "PD_HDD"
      case .obsoleteLocalSsd: return "OBSOLETE_LOCAL_SSD"
      case .hyperdiskBalanced: return "HYPERDISK_BALANCED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "SQL_DATA_DISK_TYPE_UNSPECIFIED": self = .unspecified
      case "PD_SSD": self = .pdSsd
      case "PD_HDD": self = .pdHdd
      case "OBSOLETE_LOCAL_SSD": self = .obsoleteLocalSsd
      case "HYPERDISK_BALANCED": self = .hyperdiskBalanced
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pdSsd
      case 2: self = .pdHdd
      case 3: self = .obsoleteLocalSsd
      case 4: self = .hyperdiskBalanced
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pdSsd: return try container.encode(1)
      case .pdHdd: return try container.encode(2)
      case .obsoleteLocalSsd: return try container.encode(3)
      case .hyperdiskBalanced: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }
#endif
