// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlFlagsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service to manage database flags for Cloud SQL instances.
  ///
  /// @Snippet(path: "SqlFlagsServiceQuickstart")
  public protocol SqlFlagsService {
    /// Lists all available database flags for Cloud SQL instances.
    ///
    /// @Snippet(path: "SqlFlagsService_List")
    func list(request: SqlFlagsListRequest) async throws -> GoogleCloudSqlV1.FlagsListResponse

    /// Lists all available database flags for Cloud SQL instances.
    ///
    /// @Snippet(path: "SqlFlagsService_List")
    func list(
      request: SqlFlagsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.FlagsListResponse
  }

  extension Clients {
    /// The recommended implementation for ``SqlFlagsService``.
    public class SqlFlagsServiceClient: SqlFlagsService {
      let inner: any SqlFlagsServiceStub

      /// Creates a new `SqlFlagsServiceClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any SqlFlagsServiceStub = try SqlFlagsServiceTransport(options)
        inner = SqlFlagsServiceRetry(inner, options: options)
        if let logger = options.logger {
          inner = SqlFlagsServiceLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `SqlFlagsService.list`
      public func list(
        request: SqlFlagsListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.FlagsListResponse {
        try await self.inner.list(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension SqlFlagsService {
    public func list(request: SqlFlagsListRequest) async throws
      -> GoogleCloudSqlV1.FlagsListResponse
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: SqlFlagsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.FlagsListResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }
  }
#endif
