// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlIamPoliciesService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWKT
  import GoogleCloudGax

  /// Service for providing IAM Meta APIs for Cloud SQL.
  ///
  /// @Snippet(path: "SqlIamPoliciesServiceQuickstart")
  public final class SqlIamPoliciesServiceClient: Clients.SqlIamPoliciesServiceProtocol, Sendable {
    let inner: any Clients.SqlIamPoliciesServiceStub

    /// Creates a new `SqlIamPoliciesServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlIamPoliciesServiceStub = try Clients.SqlIamPoliciesServiceTransport(
        options)
      inner = Clients.SqlIamPoliciesServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlIamPoliciesServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlIamPoliciesServiceClient`.
    ///
    /// To mock `SqlIamPoliciesServiceClient` change your functions to receive
    /// `some SqlIamPoliciesServiceProtocol` or `any SqlIamPoliciesServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlIamPoliciesServiceProtocol {
    }
  }

  // Default implementations
  extension Clients.SqlIamPoliciesServiceProtocol {
  }
#endif
