// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Instance start external sync request.
  public struct SqlInstancesStartExternalSyncRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Cloud SQL instance ID. This does not include the project ID.
    public var instance: Swift.String = Swift.String()

    /// ID of the project that contains the instance.
    public var project: Swift.String = Swift.String()

    /// External sync mode.
    public var syncMode: SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode =
      SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode()

    /// Whether to skip the verification step (VESS).
    public var skipVerification: Swift.Bool = Swift.Bool()

    /// Optional. Parallel level for initial data sync. Currently only applicable
    /// for MySQL.
    public var syncParallelLevel: ExternalSyncParallelLevel = ExternalSyncParallelLevel()

    /// Optional. MigrationType configures the migration to use physical files or
    /// logical dump files. If not set, then the logical dump file configuration is
    /// used. Valid values are `LOGICAL` or `PHYSICAL`. Only applicable to MySQL.
    public var migrationType: SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType =
      SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType()

    /// Optional. MySQL only. True if end-user has confirmed that this SES call
    /// will wipe replica databases overlapping with the proposed selected_objects.
    /// If this field is not set and there are both overlapping and additional
    /// databases proposed, an error will be returned.
    public var replicaOverwriteEnabled: Swift.Bool = Swift.Bool()

    public var syncConfig: OneOf_SyncConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SqlInstancesStartExternalSyncRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlInstancesStartExternalSyncRequest().with { $0.instance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let instance = CodingKeys(stringValue: "instance")
      static let project = CodingKeys(stringValue: "project")
      static let syncMode = CodingKeys(stringValue: "syncMode")
      static let skipVerification = CodingKeys(stringValue: "skipVerification")
      static let mysqlSyncConfig = CodingKeys(stringValue: "mysqlSyncConfig")
      static let syncParallelLevel = CodingKeys(stringValue: "syncParallelLevel")
      static let migrationType = CodingKeys(stringValue: "migrationType")
      static let replicaOverwriteEnabled = CodingKeys(stringValue: "replicaOverwriteEnabled")

      static let _knownKeys: Set<Swift.String> = [
        "instance",
        "project",
        "syncMode",
        "skipVerification",
        "mysqlSyncConfig",
        "syncParallelLevel",
        "migrationType",
        "replicaOverwriteEnabled",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instance) {
        self.instance = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        self.project = value
      }
      if let value = try container.decodeIfPresent(
        SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode.self, forKey: .syncMode)
      {
        self.syncMode = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipVerification) {
        self.skipVerification = value
      }
      if let value = try container.decodeIfPresent(
        ExternalSyncParallelLevel.self, forKey: .syncParallelLevel)
      {
        self.syncParallelLevel = value
      }
      if let value = try container.decodeIfPresent(
        SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType.self, forKey: .migrationType)
      {
        self.migrationType = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .replicaOverwriteEnabled)
      {
        self.replicaOverwriteEnabled = value
      }

      var syncConfig: OneOf_SyncConfig? = nil
      let syncConfigCheckAndSet = {
        if syncConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'syncConfig'"))
        }
        syncConfig = $0
      }
      if let mysqlSyncConfig = try container.decodeIfPresent(
        MySqlSyncConfig?.self, forKey: .mysqlSyncConfig)
      {
        try syncConfigCheckAndSet(.mysqlSyncConfig(mysqlSyncConfig))
      }
      self.syncConfig = syncConfig
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.instance, forKey: .instance)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.syncMode, forKey: .syncMode)
      try container.encode(self.skipVerification, forKey: .skipVerification)
      try container.encode(self.syncParallelLevel, forKey: .syncParallelLevel)
      try container.encode(self.migrationType, forKey: .migrationType)
      try container.encode(self.replicaOverwriteEnabled, forKey: .replicaOverwriteEnabled)

      if let choice = self.syncConfig {
        switch choice {
        case .mysqlSyncConfig(let value):
          try container.encode(value, forKey: .mysqlSyncConfig)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum OneOf_SyncConfig: Codable, Equatable, Sendable {
      /// MySQL-specific settings for start external sync.
      indirect case mysqlSyncConfig(MySqlSyncConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlInstancesStartExternalSyncRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
