// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  import GoogleCloudWkt
  import GoogleCloudGax

  extension Clients {
    protocol SqlInstancesServiceStub: Sendable {
      func addServerCa(
        request: SqlInstancesAddServerCaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func addServerCertificate(
        request: SqlInstancesAddServerCertificateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func addEntraIdCertificate(
        request: SqlInstancesAddEntraIdCertificateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func clone(
        request: SqlInstancesCloneRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func delete(
        request: SqlInstancesDeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func demoteMaster(
        request: SqlInstancesDemoteMasterRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func demote(
        request: SqlInstancesDemoteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func export(
        request: SqlInstancesExportRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func failover(
        request: SqlInstancesFailoverRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func reencrypt(
        request: SqlInstancesReencryptRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func `get`(
        request: SqlInstancesGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.DatabaseInstance

      func `import`(
        request: SqlInstancesImportRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func insert(
        request: SqlInstancesInsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func list(
        request: SqlInstancesListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.InstancesListResponse

      func listServerCas(
        request: SqlInstancesListServerCasRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.InstancesListServerCasResponse

      func listServerCertificates(
        request: SqlInstancesListServerCertificatesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.InstancesListServerCertificatesResponse

      func listEntraIdCertificates(
        request: SqlInstancesListEntraIdCertificatesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.InstancesListEntraIdCertificatesResponse

      func patch(
        request: SqlInstancesPatchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func promoteReplica(
        request: SqlInstancesPromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func switchover(
        request: SqlInstancesSwitchoverRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func resetSslConfig(
        request: SqlInstancesResetSslConfigRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func restart(
        request: SqlInstancesRestartRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func restoreBackup(
        request: SqlInstancesRestoreBackupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func rotateServerCa(
        request: SqlInstancesRotateServerCaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func rotateServerCertificate(
        request: SqlInstancesRotateServerCertificateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func rotateEntraIdCertificate(
        request: SqlInstancesRotateEntraIdCertificateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func startReplica(
        request: SqlInstancesStartReplicaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func stopReplica(
        request: SqlInstancesStopReplicaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func truncateLog(
        request: SqlInstancesTruncateLogRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func update(
        request: SqlInstancesUpdateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func createEphemeral(
        request: SqlInstancesCreateEphemeralCertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SslCert

      func rescheduleMaintenance(
        request: SqlInstancesRescheduleMaintenanceRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func verifyExternalSyncSettings(
        request: SqlInstancesVerifyExternalSyncSettingsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesVerifyExternalSyncSettingsResponse

      func startExternalSync(
        request: SqlInstancesStartExternalSyncRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func performDiskShrink(
        request: SqlInstancesPerformDiskShrinkRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func getDiskShrinkConfig(
        request: SqlInstancesGetDiskShrinkConfigRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesGetDiskShrinkConfigResponse

      func resetReplicaSize(
        request: SqlInstancesResetReplicaSizeRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func getLatestRecoveryTime(
        request: SqlInstancesGetLatestRecoveryTimeRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesGetLatestRecoveryTimeResponse

      func executeSql(
        request: SqlInstancesExecuteSqlRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesExecuteSqlResponse

      func acquireSsrsLease(
        request: SqlInstancesAcquireSsrsLeaseRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesAcquireSsrsLeaseResponse

      func releaseSsrsLease(
        request: SqlInstancesReleaseSsrsLeaseRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SqlInstancesReleaseSsrsLeaseResponse

      func preCheckMajorVersionUpgrade(
        request: SqlInstancesPreCheckMajorVersionUpgradeRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func pointInTimeRestore(
        request: SqlInstancesPointInTimeRestoreRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation
    }
  }
#endif
