// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Instance verify external sync settings request.
  public struct SqlInstancesVerifyExternalSyncSettingsRequest: Codable, Equatable, GoogleCloudWkt
      ._AnyPackable,
    Sendable
  {
    /// Cloud SQL instance ID. This does not include the project ID.
    public var instance: Swift.String = Swift.String()

    /// Project ID of the project that contains the instance.
    public var project: Swift.String = Swift.String()

    /// Flag to enable verifying connection only
    public var verifyConnectionOnly: Swift.Bool = Swift.Bool()

    /// External sync mode
    public var syncMode: SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode =
      SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode()

    /// Optional. Flag to verify settings required by replication setup only
    public var verifyReplicationOnly: Swift.Bool = Swift.Bool()

    /// Optional. MigrationType configures the migration to use physical files or
    /// logical dump files. If not set, then the logical dump file configuration is
    /// used. Valid values are `LOGICAL` or `PHYSICAL`. Only applicable to MySQL.
    public var migrationType: SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType =
      SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType()

    /// Optional. Parallel level for initial data sync. Only applicable for
    /// PostgreSQL.
    public var syncParallelLevel: ExternalSyncParallelLevel = ExternalSyncParallelLevel()

    /// Optional. Migrate only the specified objects from the source instance. If
    /// this field is empty, then migrate all objects.
    public var selectedObjects: [ExternalSyncSelectedObject] = []

    public var syncConfig: OneOf_SyncConfig? = nil

    /// Initialize a new instance of `SqlInstancesVerifyExternalSyncSettingsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlInstancesVerifyExternalSyncSettingsRequest().with { $0.instance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case instance = "instance"
      case project = "project"
      case verifyConnectionOnly = "verifyConnectionOnly"
      case syncMode = "syncMode"
      case verifyReplicationOnly = "verifyReplicationOnly"
      case mysqlSyncConfig = "mysqlSyncConfig"
      case migrationType = "migrationType"
      case syncParallelLevel = "syncParallelLevel"
      case selectedObjects = "selectedObjects"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.instance = try container.decode(Swift.String.self, forKey: .instance)
      self.project = try container.decode(Swift.String.self, forKey: .project)
      self.verifyConnectionOnly = try container.decode(
        Swift.Bool.self, forKey: .verifyConnectionOnly)
      self.syncMode = try container.decode(
        SqlInstancesVerifyExternalSyncSettingsRequest.ExternalSyncMode.self, forKey: .syncMode)
      self.verifyReplicationOnly = try container.decode(
        Swift.Bool.self, forKey: .verifyReplicationOnly)
      self.migrationType = try container.decode(
        SqlInstancesVerifyExternalSyncSettingsRequest.MigrationType.self, forKey: .migrationType)
      self.syncParallelLevel = try container.decode(
        ExternalSyncParallelLevel.self, forKey: .syncParallelLevel)
      self.selectedObjects = try container.decode(
        [ExternalSyncSelectedObject].self, forKey: .selectedObjects)

      var syncConfig: OneOf_SyncConfig? = nil
      let syncConfigCheckAndSet = {
        if syncConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'syncConfig'"))
        }
        syncConfig = $0
      }
      if let mysqlSyncConfig = try container.decodeIfPresent(
        MySqlSyncConfig?.self, forKey: .mysqlSyncConfig)
      {
        try syncConfigCheckAndSet(.mysqlSyncConfig(mysqlSyncConfig))
      }
      self.syncConfig = syncConfig
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.instance, forKey: .instance)
      try container.encode(self.project, forKey: .project)
      try container.encode(self.verifyConnectionOnly, forKey: .verifyConnectionOnly)
      try container.encode(self.syncMode, forKey: .syncMode)
      try container.encode(self.verifyReplicationOnly, forKey: .verifyReplicationOnly)
      try container.encode(self.migrationType, forKey: .migrationType)
      try container.encode(self.syncParallelLevel, forKey: .syncParallelLevel)
      try container.encode(self.selectedObjects, forKey: .selectedObjects)

      if let choice = self.syncConfig {
        switch choice {
        case .mysqlSyncConfig(let value):
          try container.encode(value, forKey: .mysqlSyncConfig)
        }
      }
    }

    public enum ExternalSyncMode: Codable, Equatable, Sendable {
      /// Unknown external sync mode, will be defaulted to ONLINE mode
      case unspecified
      /// Online external sync will set up replication after initial data external
      /// sync
      case online
      /// Offline external sync only dumps and loads a one-time snapshot of
      /// the primary instance's data
      case offline
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .online: return 1
        case .offline: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "EXTERNAL_SYNC_MODE_UNSPECIFIED"
        case .online: return "ONLINE"
        case .offline: return "OFFLINE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExternalSyncMode/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "EXTERNAL_SYNC_MODE_UNSPECIFIED": self = .unspecified
        case "ONLINE": self = .online
        case "OFFLINE": self = .offline
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExternalSyncMode/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .online
        case 2: self = .offline
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .online: return try container.encode(1)
        case .offline: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// MigrationType determines whether the migration is a physical file-based
    /// migration or a logical dump file-based migration.
    public enum MigrationType: Codable, Equatable, Sendable {
      /// Default value is a logical dump file-based migration
      case unspecified
      /// Logical dump file-based migration
      case logical
      /// Physical file-based migration
      case physical
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .logical: return 1
        case .physical: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "MIGRATION_TYPE_UNSPECIFIED"
        case .logical: return "LOGICAL"
        case .physical: return "PHYSICAL"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MigrationType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "MIGRATION_TYPE_UNSPECIFIED": self = .unspecified
        case "LOGICAL": self = .logical
        case "PHYSICAL": self = .physical
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MigrationType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .logical
        case 2: self = .physical
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .logical: return try container.encode(1)
        case .physical: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public enum OneOf_SyncConfig: Codable, Equatable, Sendable {
      /// Optional. MySQL-specific settings for start external sync.
      indirect case mysqlSyncConfig(MySqlSyncConfig?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlInstancesVerifyExternalSyncSettingsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
