// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  import GoogleCloudWkt
  import GoogleRpc

  /// Execute SQL statements response.
  public struct SqlInstancesExecuteSqlResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A list of notices and warnings generated during query execution.
    /// For PostgreSQL, this includes all notices and warnings.
    /// For MySQL, this includes warnings generated by the last executed statement.
    /// To retrieve all warnings for a multi-statement query, `SHOW WARNINGS` must
    /// be executed after each statement.
    public var messages: [SqlInstancesExecuteSqlResponse.Message]

    /// The additional metadata information regarding the execution of the SQL
    /// statements.
    public var metadata: Metadata?

    /// The list of results after executing all the SQL statements.
    public var results: [QueryResult]

    /// Contains the error from the database if the SQL execution failed.
    public var status: GoogleRpc.Status?

    /// Initialize a new instance of `SqlInstancesExecuteSqlResponse`.
    public init(
      messages: [SqlInstancesExecuteSqlResponse.Message] = [],
      metadata: Metadata? = nil,
      results: [QueryResult] = [],
      status: GoogleRpc.Status? = nil,
    ) {
      self.messages = messages
      self.metadata = metadata
      self.results = results
      self.status = status
    }

    /// Represents a notice or warning message from the database.
    public struct Message: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The full message string.
      /// For PostgreSQL, this is a formatted string that may include severity,
      /// code, and the notice/warning message.
      /// For MySQL, this contains the warning message.
      public var message: Swift.String?

      /// The severity of the message (e.g., "NOTICE" for PostgreSQL, "WARNING" for
      /// MySQL).
      public var severity: Swift.String?

      /// Initialize a new instance of `Message`.
      public init(
        message: Swift.String? = nil,
        severity: Swift.String? = nil,
      ) {
        self.message = message
        self.severity = severity
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.sql.v1.SqlInstancesExecuteSqlResponse.Message"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlInstancesExecuteSqlResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
