// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstancesService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Instance get latest recovery time response.
  public struct SqlInstancesGetLatestRecoveryTimeResponse: Codable, Equatable, GoogleWKT
      ._AnyPackable,
    Sendable
  {
    /// This is always `sql#getLatestRecoveryTime`.
    public var kind: Swift.String = Swift.String()

    /// Timestamp, identifies the latest recovery time of the source instance.
    public var latestRecoveryTime: GoogleWKT.Timestamp? = nil

    /// Timestamp, identifies the earliest recovery time of the source instance.
    public var earliestRecoveryTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SqlInstancesGetLatestRecoveryTimeResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlInstancesGetLatestRecoveryTimeResponse().with { $0.kind = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kind = CodingKeys(stringValue: "kind")
      static let latestRecoveryTime = CodingKeys(stringValue: "latestRecoveryTime")
      static let earliestRecoveryTime = CodingKeys(stringValue: "earliestRecoveryTime")

      static let _knownKeys: Set<Swift.String> = [
        "kind",
        "latestRecoveryTime",
        "earliestRecoveryTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kind) {
        self.kind = value
      }
      self.latestRecoveryTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .latestRecoveryTime)
      self.earliestRecoveryTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .earliestRecoveryTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kind, forKey: .kind)
      try container.encodeIfPresent(self.latestRecoveryTime, forKey: .latestRecoveryTime)
      try container.encodeIfPresent(self.earliestRecoveryTime, forKey: .earliestRecoveryTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlInstancesGetLatestRecoveryTimeResponse"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
