// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlInstanceNamesService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Cloud SQL instance names service.
  ///
  /// @Snippet(path: "SqlInstanceNamesServiceQuickstart")
  public protocol SqlInstanceNamesService {
  }

  extension Clients {
    /// The recommended implementation for ``SqlInstanceNamesService``.
    public class SqlInstanceNamesServiceClient: SqlInstanceNamesService {
      let inner: any SqlInstanceNamesServiceStub

      /// Creates a new `SqlInstanceNamesServiceClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any SqlInstanceNamesServiceStub = try SqlInstanceNamesServiceTransport(options)
        inner = SqlInstanceNamesServiceRetry(inner, options: options)
        if let logger = options.logger {
          inner = SqlInstanceNamesServiceLogging(inner, logger: logger)
        }
        self.inner = inner
      }
    }
  }

  // Default implementations
  extension SqlInstanceNamesService {
  }
#endif
