// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupRunsService || SqlBackupsService || SqlDatabasesService || SqlInstancesService || SqlOperationsService || SqlSslCertsService || SqlUsersService
  import Foundation

  /// The type of maintenance to be performed on the instance.
  public enum SqlMaintenanceType: Codable, Equatable, Sendable {
    /// Maintenance type is unspecified.
    case unspecified
    /// Indicates that a standalone instance is undergoing maintenance. The
    /// instance can be either a primary instance or a replica.
    case instanceMaintenance
    /// Indicates that the primary instance and all of its replicas, including
    /// cascading replicas, are undergoing maintenance. Maintenance is performed on
    /// groups of replicas first, followed by the primary instance.
    case replicaIncludedMaintenance
    /// Indicates that the standalone instance is undergoing maintenance, initiated
    /// by self-service. The instance can be either a primary instance or a
    /// replica.
    case instanceSelfServiceMaintenance
    /// Indicates that the primary instance and all of its replicas are undergoing
    /// maintenance, initiated by self-service. Maintenance is performed on groups
    /// of replicas first, followed by the primary instance.
    case replicaIncludedSelfServiceMaintenance
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .instanceMaintenance: return 1
      case .replicaIncludedMaintenance: return 2
      case .instanceSelfServiceMaintenance: return 3
      case .replicaIncludedSelfServiceMaintenance: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SQL_MAINTENANCE_TYPE_UNSPECIFIED"
      case .instanceMaintenance: return "INSTANCE_MAINTENANCE"
      case .replicaIncludedMaintenance: return "REPLICA_INCLUDED_MAINTENANCE"
      case .instanceSelfServiceMaintenance: return "INSTANCE_SELF_SERVICE_MAINTENANCE"
      case .replicaIncludedSelfServiceMaintenance:
        return "REPLICA_INCLUDED_SELF_SERVICE_MAINTENANCE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SqlMaintenanceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SQL_MAINTENANCE_TYPE_UNSPECIFIED": self = .unspecified
      case "INSTANCE_MAINTENANCE": self = .instanceMaintenance
      case "REPLICA_INCLUDED_MAINTENANCE": self = .replicaIncludedMaintenance
      case "INSTANCE_SELF_SERVICE_MAINTENANCE": self = .instanceSelfServiceMaintenance
      case "REPLICA_INCLUDED_SELF_SERVICE_MAINTENANCE":
        self = .replicaIncludedSelfServiceMaintenance
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SqlMaintenanceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .instanceMaintenance
      case 2: self = .replicaIncludedMaintenance
      case 3: self = .instanceSelfServiceMaintenance
      case 4: self = .replicaIncludedSelfServiceMaintenance
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .instanceMaintenance: return try container.encode(1)
      case .replicaIncludedMaintenance: return try container.encode(2)
      case .instanceSelfServiceMaintenance: return try container.encode(3)
      case .replicaIncludedSelfServiceMaintenance: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }
#endif
