// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlOperationsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class SqlOperationsServiceLogging: SqlOperationsServiceStub {
      let inner: any SqlOperationsServiceStub
      let logger: Logger

      public init(_ inner: any SqlOperationsServiceStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudSqlV1"
        logger[metadataKey: "gcp.client.service"] = "sqladmin"
        logger[metadataKey: "gcp.experimental.swift.client"] = "SqlOperationsService"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func `get`(
        request: SqlOperationsGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "`get`",
          action: {
            (r: SqlOperationsGetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func list(
        request: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.OperationsListResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "list",
          action: {
            (r: SqlOperationsListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.OperationsListResponse
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func cancel(
        request: SqlOperationsCancelRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancel",
          action: {
            (r: SqlOperationsCancelRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
            in
            return try await self.inner.cancel(request: r, options: o)
          })
      }
    }
  }
#endif
