// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlOperationsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service to fetch operations for database instances.
  ///
  /// @Snippet(path: "SqlOperationsServiceQuickstart")
  public class SqlOperationsServiceClient: Clients.SqlOperationsServiceProtocol {
    let inner: any Clients.SqlOperationsServiceStub

    /// Creates a new `SqlOperationsServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlOperationsServiceStub = try Clients.SqlOperationsServiceTransport(
        options)
      inner = Clients.SqlOperationsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlOperationsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Retrieves an instance operation that has been performed on an instance.
    ///
    /// @Snippet(path: "SqlOperationsService_Get")
    public func `get`(
      request: SqlOperationsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.`get`(request: request, options: options)
    }

    /// Lists all instance operations that have been performed on the given Cloud
    /// SQL instance in the reverse chronological order of the start time.
    ///
    /// @Snippet(path: "SqlOperationsService_List")
    public func list(
      request: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.OperationsListResponse {
      try await self.inner.list(request: request, options: options)
    }

    /// Lists all instance operations that have been performed on the given Cloud
    /// SQL instance in the reverse chronological order of the start time.
    ///
    /// @Snippet(path: "SqlOperationsService_List")
    public func list(
      byItem: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudSqlV1.OperationsListResponse in
        var request = byItem
        request.pageToken = token
        return try await self.list(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Cancels an instance operation that has been performed on an instance.
    ///
    /// @Snippet(path: "SqlOperationsService_Cancel")
    public func cancel(
      request: SqlOperationsCancelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancel(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlOperationsServiceClient`.
    ///
    /// To mock `SqlOperationsServiceClient` change your functions to receive
    /// `some SqlOperationsServiceProtocol` or `any SqlOperationsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlOperationsServiceProtocol {
      /// See `SqlOperationsServiceClient.`get``.
      func `get`(request: SqlOperationsGetRequest) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlOperationsServiceClient.list`.
      func list(request: SqlOperationsListRequest) async throws
        -> GoogleCloudSqlV1.OperationsListResponse

      /// See `SqlOperationsServiceClient.list`.
      func list(
        byItem: SqlOperationsListRequest
      ) throws -> any AsyncSequence<Operation, Swift.Error>

      /// See `SqlOperationsServiceClient.cancel`.
      func cancel(request: SqlOperationsCancelRequest) async throws

      /// See `SqlOperationsServiceClient.`get``.
      func `get`(
        request: SqlOperationsGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlOperationsServiceClient.list`.
      func list(
        request: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.OperationsListResponse

      /// See `SqlOperationsServiceClient.list`.
      func list(
        byItem: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Operation, Swift.Error>

      /// See `SqlOperationsServiceClient.cancel`.
      func cancel(
        request: SqlOperationsCancelRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.SqlOperationsServiceProtocol {
    public func `get`(request: SqlOperationsGetRequest) async throws -> GoogleCloudSqlV1.Operation {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: SqlOperationsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(request: SqlOperationsListRequest) async throws
      -> GoogleCloudSqlV1.OperationsListResponse
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.OperationsListResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: SqlOperationsListRequest
    ) throws -> any AsyncSequence<Operation, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: SqlOperationsListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudSqlV1.OperationsListResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func cancel(request: SqlOperationsCancelRequest) async throws {
      try await self.cancel(request: request, options: .init())
    }

    public func cancel(
      request: SqlOperationsCancelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }
  }
#endif
