// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlRegionsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service that exposes Cloud SQL region information. This service is only used
  /// internally and does not follow the same patterns as the other v1 RPCs.
  ///
  /// @Snippet(path: "SqlRegionsServiceQuickstart")
  public class SqlRegionsServiceClient: Clients.SqlRegionsServiceProtocol {
    let inner: any Clients.SqlRegionsServiceStub

    /// Creates a new `SqlRegionsServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlRegionsServiceStub = try Clients.SqlRegionsServiceTransport(options)
      inner = Clients.SqlRegionsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlRegionsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlRegionsServiceClient`.
    ///
    /// To mock `SqlRegionsServiceClient` change your functions to receive
    /// `some SqlRegionsServiceProtocol` or `any SqlRegionsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlRegionsServiceProtocol {
    }
  }

  // Default implementations
  extension Clients.SqlRegionsServiceProtocol {
  }
#endif
