// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlSslCertsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service to manage SSL certs for Cloud SQL instances.
  ///
  /// @Snippet(path: "SqlSslCertsServiceQuickstart")
  public protocol SqlSslCertsService {
    /// Deletes the SSL certificate. For First Generation instances, the
    /// certificate remains valid until the instance is restarted.
    ///
    /// @Snippet(path: "SqlSslCertsService_Delete")
    func delete(request: SqlSslCertsDeleteRequest) async throws -> GoogleCloudSqlV1.Operation

    /// Retrieves a particular SSL certificate.  Does not include the private key
    /// (required for usage).  The private key must be saved from the response to
    /// initial creation.
    ///
    /// @Snippet(path: "SqlSslCertsService_Get")
    func `get`(request: SqlSslCertsGetRequest) async throws -> GoogleCloudSqlV1.SslCert

    /// Creates an SSL certificate and returns it along with the private key and
    /// server certificate authority.  The new certificate will not be usable until
    /// the instance is restarted.
    ///
    /// @Snippet(path: "SqlSslCertsService_Insert")
    func insert(request: SqlSslCertsInsertRequest) async throws
      -> GoogleCloudSqlV1.SslCertsInsertResponse

    /// Lists all of the current SSL certificates for the instance.
    ///
    /// @Snippet(path: "SqlSslCertsService_List")
    func list(request: SqlSslCertsListRequest) async throws -> GoogleCloudSqlV1.SslCertsListResponse

    /// Deletes the SSL certificate. For First Generation instances, the
    /// certificate remains valid until the instance is restarted.
    ///
    /// @Snippet(path: "SqlSslCertsService_Delete")
    func delete(
      request: SqlSslCertsDeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation

    /// Retrieves a particular SSL certificate.  Does not include the private key
    /// (required for usage).  The private key must be saved from the response to
    /// initial creation.
    ///
    /// @Snippet(path: "SqlSslCertsService_Get")
    func `get`(
      request: SqlSslCertsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCert

    /// Creates an SSL certificate and returns it along with the private key and
    /// server certificate authority.  The new certificate will not be usable until
    /// the instance is restarted.
    ///
    /// @Snippet(path: "SqlSslCertsService_Insert")
    func insert(
      request: SqlSslCertsInsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCertsInsertResponse

    /// Lists all of the current SSL certificates for the instance.
    ///
    /// @Snippet(path: "SqlSslCertsService_List")
    func list(
      request: SqlSslCertsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCertsListResponse
  }

  extension Clients {
    /// The recommended implementation for ``SqlSslCertsService``.
    public class SqlSslCertsServiceClient: SqlSslCertsService {
      let inner: any SqlSslCertsServiceStub

      /// Creates a new `SqlSslCertsServiceClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any SqlSslCertsServiceStub = try SqlSslCertsServiceTransport(options)
        inner = SqlSslCertsServiceRetry(inner, options: options)
        if let logger = options.logger {
          inner = SqlSslCertsServiceLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `SqlSslCertsService.delete`
      public func delete(
        request: SqlSslCertsDeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `SqlSslCertsService.`get``
      public func `get`(
        request: SqlSslCertsGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SslCert {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `SqlSslCertsService.insert`
      public func insert(
        request: SqlSslCertsInsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SslCertsInsertResponse {
        try await self.inner.insert(request: request, options: options)
      }

      /// See `SqlSslCertsService.list`
      public func list(
        request: SqlSslCertsListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.SslCertsListResponse {
        try await self.inner.list(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension SqlSslCertsService {
    public func delete(request: SqlSslCertsDeleteRequest) async throws -> GoogleCloudSqlV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: SqlSslCertsDeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(request: SqlSslCertsGetRequest) async throws -> GoogleCloudSqlV1.SslCert {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: SqlSslCertsGetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCert {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(request: SqlSslCertsInsertRequest) async throws
      -> GoogleCloudSqlV1.SslCertsInsertResponse
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: SqlSslCertsInsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCertsInsertResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(request: SqlSslCertsListRequest) async throws
      -> GoogleCloudSqlV1.SslCertsListResponse
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: SqlSslCertsListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.SslCertsListResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }
  }
#endif
