// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlBackupsService || SqlInstancesService
  import Foundation

  /// The suspension reason of the database instance if the state is SUSPENDED.
  public enum SqlSuspensionReason: Codable, Equatable, Sendable {
    /// This is an unknown suspension reason.
    case unspecified
    /// The instance is suspended due to billing issues (for example:, account
    /// issue)
    case billingIssue
    /// The instance is suspended due to illegal content (for example:, child
    /// pornography, copyrighted material, etc.).
    case legalIssue
    /// The instance is causing operational issues (for example:, causing the
    /// database to crash).
    case operationalIssue
    /// The KMS key used by the instance is either revoked or denied access to
    case kmsKeyIssue
    /// The project is suspended due to abuse detected by Ares.
    case projectAbuse
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .billingIssue: return 2
      case .legalIssue: return 3
      case .operationalIssue: return 4
      case .kmsKeyIssue: return 5
      case .projectAbuse: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SQL_SUSPENSION_REASON_UNSPECIFIED"
      case .billingIssue: return "BILLING_ISSUE"
      case .legalIssue: return "LEGAL_ISSUE"
      case .operationalIssue: return "OPERATIONAL_ISSUE"
      case .kmsKeyIssue: return "KMS_KEY_ISSUE"
      case .projectAbuse: return "PROJECT_ABUSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SQL_SUSPENSION_REASON_UNSPECIFIED": self = .unspecified
      case "BILLING_ISSUE": self = .billingIssue
      case "LEGAL_ISSUE": self = .legalIssue
      case "OPERATIONAL_ISSUE": self = .operationalIssue
      case "KMS_KEY_ISSUE": self = .kmsKeyIssue
      case "PROJECT_ABUSE": self = .projectAbuse
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .billingIssue
      case 3: self = .legalIssue
      case 4: self = .operationalIssue
      case 5: self = .kmsKeyIssue
      case 8: self = .projectAbuse
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .billingIssue: return try container.encode(2)
      case .legalIssue: return try container.encode(3)
      case .operationalIssue: return try container.encode(4)
      case .kmsKeyIssue: return try container.encode(5)
      case .projectAbuse: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }
#endif
