// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlUsersService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  @_spi(GoogleCloudInternal) import GoogleCloudGax

  extension Clients {
    final class SqlUsersServiceRetry: SqlUsersServiceStub {
      let inner: any SqlUsersServiceStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any SqlUsersServiceStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func delete(
        request: SqlUsersDeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: SqlUsersDeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: SqlUsersGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.User {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: SqlUsersGetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.User
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func insert(
        request: SqlUsersInsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: SqlUsersInsertRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: SqlUsersListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.UsersListResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: SqlUsersListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.UsersListResponse
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func update(
        request: SqlUsersUpdateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: SqlUsersUpdateRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudSqlV1.Operation
            in
            return try await self.inner.update(request: r, options: o)
          })
      }
    }
  }
#endif
