// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlUsersService
  import Foundation
  import GoogleCloudWkt

  public struct SqlUsersUpdateRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Host of the user in the instance.
    public var host: Swift.String

    /// Database instance ID. This does not include the project ID.
    public var instance: Swift.String

    /// Name of the user in the instance.
    public var name: Swift.String

    /// Project ID of the project that contains the instance.
    public var project: Swift.String

    /// Optional. List of database roles to grant to the user. body.database_roles
    /// will be ignored for update request.
    public var databaseRoles: [Swift.String]

    /// Optional. Specifies whether to revoke existing roles that are not present
    /// in the `database_roles` field. If `false` or unset, the database roles
    /// specified in `database_roles` are added to the user's existing roles.
    public var revokeExistingRoles: Swift.Bool?

    public var body: User?

    /// Initialize a new instance of `SqlUsersUpdateRequest`.
    public init(
      host: Swift.String = Swift.String(),
      instance: Swift.String = Swift.String(),
      name: Swift.String = Swift.String(),
      project: Swift.String = Swift.String(),
      databaseRoles: [Swift.String] = [],
      revokeExistingRoles: Swift.Bool? = nil,
      body: User? = nil,
    ) {
      self.host = host
      self.instance = instance
      self.name = name
      self.project = project
      self.databaseRoles = databaseRoles
      self.revokeExistingRoles = revokeExistingRoles
      self.body = body
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlUsersUpdateRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
