// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlUsersService
  import Foundation
  import GoogleCloudWKT
  import GoogleCloudGax

  extension Clients {
    protocol SqlUsersServiceStub: Sendable {
      func delete(
        request: SqlUsersDeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func `get`(
        request: SqlUsersGetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.User

      func insert(
        request: SqlUsersInsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      func list(
        request: SqlUsersListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.UsersListResponse

      func update(
        request: SqlUsersUpdateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation
    }
  }
#endif
