// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlUsersService
  import Foundation
  import GoogleCloudWkt

  public struct SqlUsersUpdateRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Host of the user in the instance.
    public var host: Swift.String = Swift.String()

    /// Database instance ID. This does not include the project ID.
    public var instance: Swift.String = Swift.String()

    /// Name of the user in the instance.
    public var name: Swift.String = Swift.String()

    /// Project ID of the project that contains the instance.
    public var project: Swift.String = Swift.String()

    /// Optional. List of database roles to grant to the user. body.database_roles
    /// will be ignored for update request.
    public var databaseRoles: [Swift.String] = []

    /// Optional. Specifies whether to revoke existing roles that are not present
    /// in the `database_roles` field. If `false` or unset, the database roles
    /// specified in `database_roles` are added to the user's existing roles.
    public var revokeExistingRoles: Swift.Bool? = nil

    public var body: User? = nil

    /// Initialize a new instance of `SqlUsersUpdateRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlUsersUpdateRequest().with { $0.host = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.SqlUsersUpdateRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
