// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlWorkloadCapturesService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Cloud SQL Workload Captures service.
  ///
  /// @Snippet(path: "SqlWorkloadCapturesServiceQuickstart")
  public final class SqlWorkloadCapturesServiceClient: Clients.SqlWorkloadCapturesServiceProtocol,
    Sendable
  {
    let inner: any Clients.SqlWorkloadCapturesServiceStub

    /// Creates a new `SqlWorkloadCapturesServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.SqlWorkloadCapturesServiceStub =
        try Clients.SqlWorkloadCapturesServiceTransport(options)
      inner = Clients.SqlWorkloadCapturesServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SqlWorkloadCapturesServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Starts capturing the SQL queries, transactions, and other operations
    /// executed on the primary instance. This traffic is securely stored and forms
    /// a "captured workload". This workload can be replayed later on a different
    /// instance to safely test performance impacts, database upgrades,
    /// configuration changes etc. before applying them to production.
    ///
    /// @Snippet(path: "SqlWorkloadCapturesService_Start")
    public func start(
      request: WorkloadCapturesStartRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.start(request: request, options: options)
    }

    /// Stops capturing the query traffic and related operations executed on the
    /// primary instance.
    ///
    /// @Snippet(path: "SqlWorkloadCapturesService_Stop")
    public func stop(
      request: WorkloadCapturesStopRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.stop(request: request, options: options)
    }

    /// Starts executing a captured workload on a separate Cloud SQL instance
    /// provisioned for workload replay. This target instance simulates the
    /// production environment without affecting the primary instance.
    ///
    /// @Snippet(path: "SqlWorkloadCapturesService_StartReplay")
    public func startReplay(
      request: WorkloadCapturesStartReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.startReplay(request: request, options: options)
    }

    /// Stops an active workload replay on the target Cloud SQL replay instance.
    ///
    /// @Snippet(path: "SqlWorkloadCapturesService_StopReplay")
    public func stopReplay(
      request: WorkloadCapturesStopReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      try await self.inner.stopReplay(request: request, options: options)
    }

    /// Lists all captured workloads associated with the instance.
    ///
    /// @Snippet(path: "SqlWorkloadCapturesService_List")
    public func list(
      request: SqlWorkloadCapturesListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.WorkloadCapturesListResponse {
      try await self.inner.list(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SqlWorkloadCapturesServiceClient`.
    ///
    /// To mock `SqlWorkloadCapturesServiceClient` change your functions to receive
    /// `some SqlWorkloadCapturesServiceProtocol` or `any SqlWorkloadCapturesServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SqlWorkloadCapturesServiceProtocol: Sendable {
      /// See `SqlWorkloadCapturesServiceClient.start`.
      func start(
        request: WorkloadCapturesStartRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlWorkloadCapturesServiceClient.stop`.
      func stop(
        request: WorkloadCapturesStopRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlWorkloadCapturesServiceClient.startReplay`.
      func startReplay(
        request: WorkloadCapturesStartReplayRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlWorkloadCapturesServiceClient.stopReplay`.
      func stopReplay(
        request: WorkloadCapturesStopReplayRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.Operation

      /// See `SqlWorkloadCapturesServiceClient.list`.
      func list(
        request: SqlWorkloadCapturesListRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudSqlV1.WorkloadCapturesListResponse
    }
  }

  // Default implementations
  extension Clients.SqlWorkloadCapturesServiceProtocol {
    public func start(request: WorkloadCapturesStartRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.start(request: request, options: .init())
    }

    public func start(
      request: WorkloadCapturesStartRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func stop(request: WorkloadCapturesStopRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.stop(request: request, options: .init())
    }

    public func stop(
      request: WorkloadCapturesStopRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func startReplay(request: WorkloadCapturesStartReplayRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.startReplay(request: request, options: .init())
    }

    public func startReplay(
      request: WorkloadCapturesStartReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func stopReplay(request: WorkloadCapturesStopReplayRequest) async throws
      -> GoogleCloudSqlV1.Operation
    {
      try await self.stopReplay(request: request, options: .init())
    }

    public func stopReplay(
      request: WorkloadCapturesStopReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func list(request: SqlWorkloadCapturesListRequest) async throws
      -> GoogleCloudSqlV1.WorkloadCapturesListResponse
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: SqlWorkloadCapturesListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSqlV1.WorkloadCapturesListResponse {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'SqlWorkloadCapturesService' trait in Package.swift to use this client."
  )
  public final class SqlWorkloadCapturesServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'SqlWorkloadCapturesService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
