// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BlueGreenDeploymentsService || SqlBackupRunsService || SqlBackupsService || SqlDatabasesService || SqlInstancesService || SqlOperationsService || SqlSslCertsService || SqlUsersService || SqlWorkloadCapturesService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The context for the `StartWorkloadCapture` operation, which contains
  /// details to start recording the workload (SQL queries) on a Cloud SQL
  /// instance.
  public struct StartWorkloadCaptureContext: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. If true, the captured workload is simultaneously executed on a
    /// separate, ephemeral Cloud SQL instance. This "live replay" instance
    /// is automatically provisioned and is cloned from the source instance. If
    /// false (the default), the workload is only stored and no live replay occurs.
    /// It can be replayed later using a separate `StartWorkloadReplayRequest`.
    /// Note: The workload capture runs continuously until an explicit
    /// `StopWorkloadCaptureRequest` is issued.
    public var enableLiveReplay: Swift.Bool = Swift.Bool()

    /// Optional. Required if `enable_live_replay` is true.
    /// The name of the Cloud SQL instance where the captured workload
    /// (SQL queries) is being executed, excluding the project ID (for example,
    /// `my-replay-instance`). The instance name must start with a lowercase letter
    /// and contain only lowercase letters, numbers, and hyphens. The combined
    /// length of `project-ID:instance-name` must be 98 characters or less.
    public var replayInstance: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StartWorkloadCaptureContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StartWorkloadCaptureContext().with { $0.enableLiveReplay = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enableLiveReplay = CodingKeys(stringValue: "enableLiveReplay")
      static let replayInstance = CodingKeys(stringValue: "replayInstance")

      static let _knownKeys: Set<Swift.String> = [
        "enableLiveReplay",
        "replayInstance",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableLiveReplay) {
        self.enableLiveReplay = value
      }
      self.replayInstance = try container.decodeIfPresent(
        Swift.String.self, forKey: .replayInstance)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enableLiveReplay, forKey: .enableLiveReplay)
      try container.encodeIfPresent(self.replayInstance, forKey: .replayInstance)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `StartWorkloadCaptureContext`: `"type.googleapis.com/google.cloud.sql.v1.StartWorkloadCaptureContext"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.StartWorkloadCaptureContext"
    }

    /// Initialize an instance of `StartWorkloadCaptureContext` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.sql.v1.StartWorkloadCaptureContext"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `StartWorkloadCaptureContext` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
