// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlUsersService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// User level password validation policy.
  public struct UserPasswordValidationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Number of failed login attempts allowed before user get locked.
    public var allowedFailedAttempts: Swift.Int32 = Swift.Int32()

    /// Expiration duration after password is updated.
    public var passwordExpirationDuration: GoogleWKT.Duration? = nil

    /// If true, failed login attempts check will be enabled.
    public var enableFailedAttemptsCheck: Swift.Bool = Swift.Bool()

    /// Output only. Read-only password status.
    public var status: PasswordStatus? = nil

    /// If true, the user must specify the current password before changing the
    /// password. This flag is supported only for MySQL.
    public var enablePasswordVerification: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UserPasswordValidationPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserPasswordValidationPolicy().with { $0.allowedFailedAttempts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allowedFailedAttempts = CodingKeys(stringValue: "allowedFailedAttempts")
      static let passwordExpirationDuration = CodingKeys(stringValue: "passwordExpirationDuration")
      static let enableFailedAttemptsCheck = CodingKeys(stringValue: "enableFailedAttemptsCheck")
      static let status = CodingKeys(stringValue: "status")
      static let enablePasswordVerification = CodingKeys(stringValue: "enablePasswordVerification")

      static let _knownKeys: Set<Swift.String> = [
        "allowedFailedAttempts",
        "passwordExpirationDuration",
        "enableFailedAttemptsCheck",
        "status",
        "enablePasswordVerification",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .allowedFailedAttempts)
      {
        self.allowedFailedAttempts = value
      }
      self.passwordExpirationDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .passwordExpirationDuration)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enableFailedAttemptsCheck)
      {
        self.enableFailedAttemptsCheck = value
      }
      self.status = try container.decodeIfPresent(PasswordStatus.self, forKey: .status)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enablePasswordVerification)
      {
        self.enablePasswordVerification = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.allowedFailedAttempts, forKey: .allowedFailedAttempts)
      try container.encodeIfPresent(
        self.passwordExpirationDuration, forKey: .passwordExpirationDuration)
      try container.encode(self.enableFailedAttemptsCheck, forKey: .enableFailedAttemptsCheck)
      try container.encodeIfPresent(self.status, forKey: .status)
      try container.encode(self.enablePasswordVerification, forKey: .enablePasswordVerification)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.UserPasswordValidationPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
