// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SqlWorkloadCapturesService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Captured workload for an instance.
  public struct WorkloadCapture: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The ID of the captured workload.
    public var workloadId: Swift.String = Swift.String()

    /// Output only. The name of the source instance.
    public var sourceInstance: Swift.String = Swift.String()

    /// Output only. The state of the workload capture.
    public var workloadCaptureState: WorkloadCapture.State = WorkloadCapture.State()

    /// Output only. The start time of the workload capture.
    public var startTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The end time of the workload capture.
    public var endTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The name of the replay instance, if live replay was enabled.
    public var replayInstance: Swift.String? = nil

    /// Output only. The retention period in days for the captured workload.
    public var retentionDays: Swift.Int32? = nil

    /// Output only. The base backup ID associated with the workload capture.
    public var backupId: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WorkloadCapture`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkloadCapture().with { $0.workloadId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let workloadId = CodingKeys(stringValue: "workloadId")
      static let sourceInstance = CodingKeys(stringValue: "sourceInstance")
      static let workloadCaptureState = CodingKeys(stringValue: "workloadCaptureState")
      static let startTime = CodingKeys(stringValue: "startTime")
      static let endTime = CodingKeys(stringValue: "endTime")
      static let replayInstance = CodingKeys(stringValue: "replayInstance")
      static let retentionDays = CodingKeys(stringValue: "retentionDays")
      static let backupId = CodingKeys(stringValue: "backupId")

      static let _knownKeys: Set<Swift.String> = [
        "workloadId",
        "sourceInstance",
        "workloadCaptureState",
        "startTime",
        "endTime",
        "replayInstance",
        "retentionDays",
        "backupId",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workloadId) {
        self.workloadId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceInstance) {
        self.sourceInstance = value
      }
      if let value = try container.decodeIfPresent(
        WorkloadCapture.State.self, forKey: .workloadCaptureState)
      {
        self.workloadCaptureState = value
      }
      self.startTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTime)
      self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
      self.replayInstance = try container.decodeIfPresent(
        Swift.String.self, forKey: .replayInstance)
      self.retentionDays = try container.decodeIfPresent(Swift.Int32.self, forKey: .retentionDays)
      self.backupId = try container.decodeIfPresent(Swift.String.self, forKey: .backupId)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.workloadId, forKey: .workloadId)
      try container.encode(self.sourceInstance, forKey: .sourceInstance)
      try container.encode(self.workloadCaptureState, forKey: .workloadCaptureState)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      try container.encodeIfPresent(self.replayInstance, forKey: .replayInstance)
      try container.encodeIfPresent(self.retentionDays, forKey: .retentionDays)
      try container.encodeIfPresent(self.backupId, forKey: .backupId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// State of the workload capture.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// Workload capture is currently running.
      case running
      /// Workload capture completed successfully. This state is set when the user
      /// explicitly stops the capture.
      case completed
      /// Workload capture failed.
      case failed
      /// Workload capture was terminated automatically. This state is set when
      /// Cloud SQL automatically stops the capture due to a conflicting operation
      /// or when the maximum duration is reached.
      case terminated
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .running: return 1
        case .completed: return 2
        case .failed: return 3
        case .terminated: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .running: return "RUNNING"
        case .completed: return "COMPLETED"
        case .failed: return "FAILED"
        case .terminated: return "TERMINATED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "RUNNING": self = .running
        case "COMPLETED": self = .completed
        case "FAILED": self = .failed
        case "TERMINATED": self = .terminated
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .running
        case 2: self = .completed
        case 3: self = .failed
        case 4: self = .terminated
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .running: return try container.encode("RUNNING")
        case .completed: return try container.encode("COMPLETED")
        case .failed: return try container.encode("FAILED")
        case .terminated: return try container.encode("TERMINATED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `WorkloadCapture`: `"type.googleapis.com/google.cloud.sql.v1.WorkloadCapture"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.sql.v1.WorkloadCapture"
    }

    /// Initialize an instance of `WorkloadCapture` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.sql.v1.WorkloadCapture"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `WorkloadCapture` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
